import pytest

pytestmark = pytest.mark.unit

from dartlab.providers.dart.docs.sections.mapper import (
    loadSectionMappings,
    mapSectionTitle,
    normalizeSectionTitle,
    stripSectionPrefix,
)


def test_normalize_section_title_strips_prefix_and_spaces():
    value = normalizeSectionTitle(" 1. 회사의 법적ㆍ상업적 명칭 ")
    assert value == "회사의법적,상업적명칭"


def test_normalize_section_title_handles_industry_then_number_prefix():
    value = normalizeSectionTitle("(제조서비스업) 2. 매출 및 수주상황")
    assert value == "매출및수주상황"


def test_normalize_section_title_handles_parenthesized_number_prefix():
    value = normalizeSectionTitle("(1) 연구개발실적(상세)")
    assert value == "연구개발실적(상세)"


def test_normalize_section_title_handles_middle_dot_and_trailing_punct():
    value = normalizeSectionTitle("1. 회사의 법적·상업적 명칭-")
    assert value == "회사의법적,상업적명칭"


def test_strip_section_prefix_handles_multiple_number_styles():
    assert stripSectionPrefix("가) 주요 제품 및 서비스") == "주요 제품 및 서비스"
    assert stripSectionPrefix("1) 사업의 개요") == "사업의 개요"
    assert stripSectionPrefix("① 재무제표") == "재무제표"


def test_section_mapping_loaded():
    mapping = loadSectionMappings()
    assert isinstance(mapping, dict)
    assert len(mapping) > 0


def test_map_section_title_returns_known_canonical_topic():
    mapped = mapSectionTitle("1. 사업의 개요")
    assert mapped == "businessOverview"


def test_map_section_title_returns_new_legacy_canonical_topics():
    assert mapSectionTitle("배당에관한사항등") == "dividend"
    assert mapSectionTitle("당해회사의연혁") == "companyHistory"
    assert mapSectionTitle("조직개편") == "companyHistory"
    assert mapSectionTitle("회사의업종또는주된사업의변화") == "companyHistory"
    assert mapSectionTitle("자본금변동상황") == "capitalChange"
    assert mapSectionTitle("임원및직원의현황") == "employee"
    assert mapSectionTitle("의결권현황") == "shareCapital"
    assert mapSectionTitle("주식의총수") == "shareCapital"
    assert mapSectionTitle("소액주주현황") == "shareCapital"
    assert mapSectionTitle("소수주주권") == "shareholderMeeting"
    assert mapSectionTitle("주주총회의사록요약") == "shareholderMeeting"
    assert mapSectionTitle("투표제도") == "shareholderMeeting"
    assert mapSectionTitle("전문가와의이해관계") == "expertConfirmation"
    assert mapSectionTitle("신용평가에관한사항") == "creditRating"
    assert mapSectionTitle("영업실적") == "businessStatus"
    assert mapSectionTitle("매출실적") == "salesOrder"
    assert mapSectionTitle("판매경로") == "salesOrder"
    assert mapSectionTitle("주요매출처") == "salesOrder"
    assert mapSectionTitle("연구개발실적") == "majorContractsAndRnd"
    assert mapSectionTitle("연구개발조직및운영") == "majorContractsAndRnd"
    assert mapSectionTitle("연구개발활동의개요") == "majorContractsAndRnd"
    assert mapSectionTitle("연구개발담당조직") == "majorContractsAndRnd"
    assert mapSectionTitle("설립일자") == "companyOverview"
    assert mapSectionTitle("향후추진하고자하는사업") == "companyOverview"
    assert mapSectionTitle("신규사업에관한내용") == "companyOverview"
    assert mapSectionTitle("신규사업") == "companyOverview"
    assert mapSectionTitle("회사의법적,상업적명칭") == "companyOverview"
    assert mapSectionTitle("회사의법적·상업적명칭") == "companyOverview"
    assert mapSectionTitle("본사의주소,전화번호,홈페이지주소") == "companyOverview"
    assert mapSectionTitle("회사의본점소재지및그변경") == "companyOverview"
    assert mapSectionTitle("설립일자및존속기간") == "companyOverview"
    assert mapSectionTitle("신규사업및중단사업") == "companyOverview"
    assert mapSectionTitle("본사의주소등") == "companyOverview"
    assert mapSectionTitle("본점소재지및그변경") == "companyOverview"
    assert mapSectionTitle("주요사업의내용및향후추진하려는신규사업") == "companyOverview"
    assert mapSectionTitle("중요한신규사업의내용과전망") == "companyOverview"
    assert mapSectionTitle("회사가속해있는기업집단") == "affiliateGroup"
    assert mapSectionTitle("기업집단및소속회사의명칭") == "affiliateGroup"
    assert mapSectionTitle("기업집단의개요") == "affiliateGroup"
    assert mapSectionTitle("기업집단의명칭및소속회사의명칭") == "affiliateGroup"
    assert mapSectionTitle("관계회사등의현황") == "affiliateGroup"
    assert mapSectionTitle("회사의현황") == "companyOverview"
    assert mapSectionTitle("작성기준일이후발생한주요사항") == "subsequentEvents"
    assert mapSectionTitle("지적재산권관련") == "intellectualProperty"
    assert mapSectionTitle("환경관련규제사항") == "environmentRegulation"
    assert mapSectionTitle("법규상의규제에관한사항") == "environmentRegulation"
    assert mapSectionTitle("환경및종업원등에관한사항") == "environmentRegulation"
    assert mapSectionTitle("환경보호정책및현황") == "environmentRegulation"
    assert mapSectionTitle("환경물질의배출또는환경보호와관련된사항등") == "environmentRegulation"
    assert mapSectionTitle("관련법령또는정부의규제등") == "environmentRegulation"
    assert mapSectionTitle("배출권거래제관리업체지정") == "environmentRegulation"
    assert (
        mapSectionTitle("또한당사는환경안전관련법규준수를위해내부관리기준을강화하고임직원") == "environmentRegulation"
    )
    assert mapSectionTitle("중소기업해당여부") == "smeStatus"
    assert mapSectionTitle("경영권경쟁") == "controlCompetition"
    assert mapSectionTitle("자기주식") == "treasuryStock"
    assert mapSectionTitle("판매경로및판매방법등") == "salesOrder"
    assert mapSectionTitle("판매경로,방법및전략") == "salesOrder"
    assert mapSectionTitle("판매경로,방법및전략등") == "salesOrder"
    assert mapSectionTitle("판매경로및판매전략") == "salesOrder"
    assert mapSectionTitle("시장위험") == "marketRisk"
    assert mapSectionTitle("신용위험") == "creditRisk"
    assert mapSectionTitle("유동성위험") == "liquidityRisk"
    assert mapSectionTitle("유동성현황") == "liquidityRisk"
    assert mapSectionTitle("자본위험관리") == "capitalRisk"
    assert mapSectionTitle("재무위험관리정책") == "riskDerivative"
    assert mapSectionTitle("주요재무위험관리") == "riskDerivative"
    assert mapSectionTitle("공정가치측정") == "riskDerivative"
    assert mapSectionTitle("파생상품및풋백옵션등거래현황") == "riskDerivative"
    assert mapSectionTitle("중요한소송사건등") == "materialLitigation"
    assert mapSectionTitle("견질또는담보용어음,수표현황") == "pledgedNotesAndChecks"
    assert mapSectionTitle("독점규제및공정거래에관한법률상특수관계인을상대로") == "relatedPartyCompetitionLaw"
    assert mapSectionTitle("다양한종류의주식") == "shareClassDiversity"
    assert mapSectionTitle("연결대상종속기업개황") == "subsidiaryDetail"
    assert mapSectionTitle("연결대상종속회사개황") == "subsidiaryDetail"
    assert mapSectionTitle("연결대상종속회사현황(요약)") == "subsidiaryDetail"
    assert mapSectionTitle("자회사의사업현황") == "subsidiaryDetail"
    assert mapSectionTitle("합병전,후의재무제표") == "companyHistory"
    assert mapSectionTitle("이사회제도에관한사항") == "boardOfDirectors"
    assert mapSectionTitle("기타이사회가필요하다고인정하는위원회") == "boardOfDirectors"
    assert mapSectionTitle("이사회등회사의기관의개요") == "boardOfDirectors"
    assert mapSectionTitle("이사회구성의개요") == "boardOfDirectors"
    assert mapSectionTitle("이사회내위원회") == "boardOfDirectors"
    assert mapSectionTitle("사외이사의전문성") == "boardOfDirectors"
    assert mapSectionTitle("자회사가영위하는목적사업") == "articlesOfIncorporation"
    assert mapSectionTitle("회사가영위하지아니하는목적사업") == "articlesOfIncorporation"
    assert mapSectionTitle("사업목적변경") == "articlesOfIncorporation"
    assert mapSectionTitle("정관변경이력") == "articlesOfIncorporation"
    assert mapSectionTitle("주요원재료가격변동추이") == "rawMaterialPriceTrend"
    assert mapSectionTitle("주요원재료현황") == "rawMaterial"
    assert mapSectionTitle("주요원재료의매입처및원재료공급시장과공급의안정성") == "rawMaterial"
    assert mapSectionTitle("생산능력및생산능력의산출근거") == "rawMaterial"
    assert mapSectionTitle("생산설비의현황") == "rawMaterial"
    assert mapSectionTitle("생산설비의현황등") == "rawMaterial"
    assert mapSectionTitle("생산실적및가동률") == "rawMaterial"
    assert mapSectionTitle("기타의우발채무등") == "contingentLiability"
    assert mapSectionTitle("채무보증현황") == "contingentLiability"
    assert mapSectionTitle("채무인수약정현황") == "contingentLiability"
    assert mapSectionTitle("우발채무및약정사항") == "contingentLiability"
    assert mapSectionTitle("기타의우발부채등") == "contingentLiability"
    assert mapSectionTitle("담보제공내역") == "contingentLiability"
    assert mapSectionTitle("주식선택권의부여및행사현황") == "stockOption"
    assert mapSectionTitle("주식매수선택권의부여및행사현황") == "stockOption"
    assert mapSectionTitle("스톡그랜트") == "stockOption"
    assert mapSectionTitle("주권상장(또는등록,지정)여부및특례상장에관한사항") == "listingStatus"
    assert mapSectionTitle("참고사항") == "otherReference"
    assert mapSectionTitle("기타중요한사항") == "otherReference"
    assert mapSectionTitle("그밖에경영활동과관련된중요한사항의발생내용") == "otherReference"
    assert mapSectionTitle("양도목적:당사3대신성장사업에집중하기위한사업포트폴리오조정") == "otherReference"
    assert mapSectionTitle("중간감사") == "audit"
    assert mapSectionTitle("자산손상인식") == "financialNotes"
    assert mapSectionTitle("자산감액손실인식") == "financialNotes"
    assert mapSectionTitle("주요시장위험내용") == "marketRisk"
    assert mapSectionTitle("범주별금융상품") == "financialNotes"
    assert mapSectionTitle("재무제표이용상의유의점") == "financialNotes"
    assert mapSectionTitle("회계정보에관한사항") == "financialNotes"
    assert mapSectionTitle("유가증권명세서") == "financialNotes"
    assert mapSectionTitle("주요채권명세서") == "financialNotes"
    assert mapSectionTitle("사채명세서") == "financialNotes"
    assert mapSectionTitle("장기차입금명세서") == "financialNotes"
    assert mapSectionTitle("단기차입금명세서") == "financialNotes"
    assert mapSectionTitle("주요채무명세서") == "financialNotes"
    assert mapSectionTitle("예금등명세서") == "financialNotes"
    assert mapSectionTitle("유형자산") == "financialNotes"
    assert mapSectionTitle("재무상태") == "financialNotes"
    assert mapSectionTitle("금융부채") == "financialNotes"
    assert mapSectionTitle("금융자산") == "financialNotes"
    assert mapSectionTitle("중요한회계정책및추정에관한사항") == "financialNotes"
    assert mapSectionTitle("타법인출자현황") == "investmentInOtherDetail"
    assert mapSectionTitle("유가증권매수또는매도내역") == "investmentInOtherDetail"
    assert mapSectionTitle("출자및출자지분처분내역") == "investmentInOtherDetail"
    assert mapSectionTitle("최근3사업연도배당에관한사항") == "dividend"
    assert mapSectionTitle("최근5사업연도의배당에관한사항") == "dividend"
    assert mapSectionTitle("공모자금사용내역") == "fundraising"
    assert mapSectionTitle("이익참가부사채에관한사항") == "fundraising"
    assert mapSectionTitle("이익참가부사채") == "fundraising"
    assert mapSectionTitle("환율변동영향") == "riskDerivative"
    assert mapSectionTitle("환위험관리대책") == "riskDerivative"
    assert mapSectionTitle("시장위험과위험관리") == "riskDerivative"
    assert mapSectionTitle("시장위험과위험관리에관한사항") == "riskDerivative"
    assert mapSectionTitle("회사의위험관리정책") == "riskDerivative"
    assert mapSectionTitle("위험관리방식및조직") == "riskDerivative"
    assert mapSectionTitle("파생금융상품거래현황") == "riskDerivative"
    assert mapSectionTitle("리스크관리에관한사항") == "riskDerivative"
    assert mapSectionTitle("파생상품") == "riskDerivative"
    assert mapSectionTitle("파생상품계약체결현황") == "riskDerivative"
    assert mapSectionTitle("파생상품및위험관리정책에관한사항") == "riskDerivative"
    assert mapSectionTitle("회계감사인의감사의견등") == "audit"
    assert mapSectionTitle("결산감사") == "audit"
    assert mapSectionTitle("회계감사인의변경") == "audit"
    assert mapSectionTitle("회계감사인의명칭및감사의견") == "audit"
    assert mapSectionTitle("감사인") == "audit"
    assert mapSectionTitle("외부감사인과의비감사용역계약체결현황") == "audit"
    assert mapSectionTitle("감사인(공인회계사)의감사의견등") == "audit"
    assert mapSectionTitle("감사의견") == "audit"
    assert mapSectionTitle("감사절차요약") == "audit"
    assert mapSectionTitle("당해사업연도의감사(검토)절차요약") == "audit"
    assert mapSectionTitle("당해사업연도의반기감사(또는검토)절차요약") == "audit"
    assert mapSectionTitle("당해사업연도의연결감사(검토)절차요약") == "audit"
    assert mapSectionTitle("당해사업연도의감사절차요약") == "audit"
    assert mapSectionTitle("당해사업연도의분기감사(또는검토)절차요약") == "audit"
    assert mapSectionTitle("연결재무제표에대한감사인의감사의견등") == "audit"
    assert mapSectionTitle("연결감사의견") == "audit"
    assert mapSectionTitle("당해사업연도감사(내부감사)의감사의견등") == "auditSystem"
    assert mapSectionTitle("한국거래소등으로부터받은제재현황") == "sanction"
    assert mapSectionTitle("행정기관의제재현황") == "sanction"
    assert mapSectionTitle("수사,사법기관의제재현황") == "sanction"
    assert mapSectionTitle("금융감독당국의제재현황") == "sanction"
    assert mapSectionTitle("임원의보수") == "executivePay"
    assert mapSectionTitle("임원배상책임보험가입현황") == "executiveLiabilityInsurance"
    assert mapSectionTitle("최대주주의개요") == "majorHolder"
    assert mapSectionTitle("최대주주의최대주주의개요") == "majorHolder"
    assert mapSectionTitle("회사의최대주주(그의증권거래법상특수관계인을포함한다)") == "majorHolder"
    assert mapSectionTitle("최대주주의변동을초래할수있는특정거래") == "majorHolder"
    assert mapSectionTitle("최대주주의변동") == "majorHolder"
    assert mapSectionTitle("최대주주변동내역") == "majorHolder"
    assert mapSectionTitle("최대주주의주요경력및개요") == "majorHolder"
    assert mapSectionTitle("최대주주의재무현황") == "majorHolder"
    assert mapSectionTitle("최대주주및그지분율") == "majorHolder"
    assert mapSectionTitle("최대주주및특수관계인의주식소유현황") == "majorHolder"
    assert mapSectionTitle("최대주주상세") == "majorHolder"
    assert mapSectionTitle("최대주주개요") == "majorHolder"
    assert mapSectionTitle("최대주주(법인또는단체)의기본정보") == "majorHolder"
    assert mapSectionTitle("5%이상주주의주식소유현황") == "majorHolder"
    assert mapSectionTitle("자금조달과지출") == "liquidityAndCapitalResources"
    assert mapSectionTitle("자금조달") == "liquidityAndCapitalResources"
    assert mapSectionTitle("투자계획") == "liquidityAndCapitalResources"
    assert mapSectionTitle("외부자금조달요약표") == "liquidityAndCapitalResources"
    assert mapSectionTitle("주요경영사항신고내용의진행상황등") == "disclosureChanges"
    assert mapSectionTitle("주요경영사항신고내용및그진행상황") == "disclosureChanges"
    assert mapSectionTitle("장래계획에관한사항의추진실적") == "disclosureChanges"
    assert mapSectionTitle("사업부문별현황") == "segmentOverview"
    assert mapSectionTitle("각사업부문별산업분석") == "segmentOverview"
    assert mapSectionTitle("각사업부문의시장여건및영업의개황등") == "segmentOverview"
    assert mapSectionTitle("부문별재무현황") == "segmentFinancialSummary"
    assert mapSectionTitle("디지털및생활가전") == "segmentHomeAppliance"
    assert mapSectionTitle("반도체") == "segmentSemiconductor"
    assert mapSectionTitle("정보통신") == "segmentIct"
    assert mapSectionTitle("디지털미디어") == "segmentDigitalMedia"
    assert mapSectionTitle("생활가전") == "segmentHomeAppliance"
    assert mapSectionTitle("이사회구성개요") == "boardOfDirectors"
    assert mapSectionTitle("감사위원회위원의독립성") == "auditSystem"
    assert mapSectionTitle("감사위원회의인적사항") == "auditSystem"
    assert mapSectionTitle("감사위원회에관한사항") == "auditSystem"
    assert mapSectionTitle("교육실시계획") == "auditSystem"
    assert mapSectionTitle("교육실시현황") == "auditSystem"
    assert mapSectionTitle("계열회사에관한사항") == "affiliateGroup"
    assert mapSectionTitle("관계기업및자회사의지분현황") == "affiliateGroupDetail"
    assert mapSectionTitle("관계회사및자회사의지분현황") == "affiliateGroupDetail"
    assert mapSectionTitle("계열회사간출자현황") == "affiliateGroupDetail"
    assert mapSectionTitle("계열회사등관리조직현황") == "affiliateGroup"
    assert mapSectionTitle("회사와계열회사간임원겸직현황") == "boardOfDirectors"
    assert mapSectionTitle("외국지주회사의자회사현황") == "subsidiaryDetail"


def test_map_section_title_handles_company_prefixed_detail_patterns():
    assert mapSectionTitle("[한국수력원자력(주)]연구개발실적(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("한국중부발전(주)주요연구개발실적(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("연구개발진행현황-SK바이오팜") == "majorContractsAndRnd"
    assert mapSectionTitle("핵심연구인력현황-SK바이오팜") == "majorContractsAndRnd"
    assert mapSectionTitle("포스코건설수주현황(상세)") == "salesOrder"
    assert mapSectionTitle("4-2.사업의개요-판매조건및경로,판매전략,주요매출처(상세)") == "salesOrder"
    assert mapSectionTitle("수주현황") == "salesOrder"
    assert mapSectionTitle("[한국수력원자력(주)]경영상의주요계약(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("주요계약및연구개발활동(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("주요연구개발과제및실적(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("연구개발현황(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("연구개발활동(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("SK바이오팜지적재산권보유현황(상세)") == "intellectualProperty"
    assert mapSectionTitle("지적재선권보유현황-SK바이오팜") == "intellectualProperty"
    assert mapSectionTitle("주요특허현황(상세)") == "intellectualProperty"
    assert mapSectionTitle("4-5.사업의개요-지적재산권(상세)") == "intellectualProperty"
    assert mapSectionTitle("주요지적재산권내용") == "intellectualProperty"
    assert mapSectionTitle("지적재산권(상세)") == "intellectualProperty"
    assert mapSectionTitle("신용파생상품거래현황(상세)") == "riskDerivative"
    assert mapSectionTitle("신용파생상품상세명세") == "riskDerivative"
    assert mapSectionTitle("이자율스왑의계약내용(상세)") == "riskDerivative"
    assert mapSectionTitle("일임형Wrap상품(상세)") == "productService"
    assert mapSectionTitle("예금상품별개요") == "productService"
    assert mapSectionTitle("주요모바일요금제-㈜스카이라이프") == "productService"
    assert mapSectionTitle("주요상품,서비스(3)신탁상품(상세)") == "productService"
    assert mapSectionTitle("4-4.주요상품및서비스-전자금융업무(상세)") == "productService"
    assert mapSectionTitle("생산설비의현황(상세)") == "rawMaterial"
    assert mapSectionTitle("해외생산설비현황(상세)") == "rawMaterial"
    assert mapSectionTitle("(LX인터내셔널)물류부문영업설비현황(국내)") == "rawMaterial"
    assert mapSectionTitle("감사보고서") == "audit"
    assert mapSectionTitle("외부감사실시내용") == "audit"
    assert mapSectionTitle("연결내부회계관리제도감사또는검토의견") == "internalControl"
    assert mapSectionTitle("(첨부)연결재무제표") == "financialNotes"
    assert mapSectionTitle("주석") == "financialNotes"
    assert mapSectionTitle("국내및해외주요사업장현황(상세)") == "companyOverview"
    assert mapSectionTitle("개별재무제표에관한사항") == "financialNotes"
    assert mapSectionTitle("연결재무제표에관한사항") == "financialNotes"
    assert mapSectionTitle("법인세비용명세서") == "financialNotes"
    assert mapSectionTitle("개별재무제표에대한감사인(공인회계사)의감사의견등") == "audit"
    assert mapSectionTitle("중간감사") == "audit"
    assert mapSectionTitle("컴퓨터2000년문제의해결과관련된사항") == "otherReference"
    assert mapSectionTitle("지적재산권보유현황(에코프로머티리얼즈)") == "intellectualProperty"
    assert mapSectionTitle("지적재산권보유현황") == "intellectualProperty"
    assert mapSectionTitle("연구개발실적(에코프로머티리얼즈)") == "majorContractsAndRnd"
    assert mapSectionTitle("주요지적재산권현황(상세)") == "intellectualProperty"
    assert mapSectionTitle("수주상황(상세)") == "salesOrder"
    assert mapSectionTitle("수주현황(상세)") == "salesOrder"
    assert mapSectionTitle("경영상의주요계약(상세)") == "majorContractsAndRnd"
    assert mapSectionTitle("경영상의주요계약[상세]") == "majorContractsAndRnd"
    assert mapSectionTitle("투자매매업무-장내파생상품거래현황(상세)") == "riskDerivative"
    assert mapSectionTitle("(하나증권)신용파생상품상세명세(상세)") == "riskDerivative"
    assert mapSectionTitle("투자매매업무-증권거래현황(상세)") == "productService"
    assert mapSectionTitle("투자중개업무-금융투자상품의위탁매매및수수료현황(상세)") == "productService"
    assert mapSectionTitle("(하나은행)예금업무(상세)") == "productService"
    assert mapSectionTitle("(하나카드)신용카드상품(상세)") == "productService"
    assert mapSectionTitle("(하나은행)신탁업무(상세)") == "productService"
    assert mapSectionTitle("(하나은행)외환/수출입서비스(상세)") == "productService"
    assert mapSectionTitle("(하나은행)기타업무-e-금융서비스(상세)") == "productService"
    assert mapSectionTitle("(하나저축은행)상품및서비스개요(상세)") == "productService"
    assert mapSectionTitle("(하나증권)신용파생상품상세명세") == "riskDerivative"
    assert mapSectionTitle("신탁업무-재무제표(상세)") == "financialNotes"
    assert mapSectionTitle("기업집단에소속된회사(상세)") == "affiliateGroupDetail"
    assert mapSectionTitle("지배구조의개요") == "governanceOverview"
    assert mapSectionTitle("회사의중·장기전략") == "companyOverview"
    assert mapSectionTitle("중요한소송사건") == "materialLitigation"
    assert mapSectionTitle("사업부문별재무정보") == "segmentFinancialSummary"
    assert mapSectionTitle("각사업부문별주요재무정보요약") == "segmentFinancialSummary"
    assert mapSectionTitle("단기매매차익발생및반환에관한사항") == "shortSwingProfit"
    assert mapSectionTitle("단기매매차익의발생및반환에관한사항") == "shortSwingProfit"
    assert mapSectionTitle("주식사무") == "stockAdministration"
    assert mapSectionTitle("내부통제유효성감사") == "internalControl"
    assert mapSectionTitle("내부통제") == "internalControl"
    assert mapSectionTitle("내부통제구조의평가") == "internalControl"
    assert mapSectionTitle("최근6개월간의주가및주식거래실적") == "stockPriceTrend"
    assert mapSectionTitle("주식소유현황") == "shareCapital"
