"""quant 31축 레지스트리 + 한글/영문 alias 테이블 + 그룹 정의 SSOT.

quant/__init__.py 가 911 줄 god module 이라 데이터 부분만 분리.
identity 보존을 위해 __init__.py 가 본 모듈에서 re-export 한다.

내용:
- _AxisEntry — 축 메타 dataclass
- _AXIS_REGISTRY — 31 축 정의 (technical · risk · microstructure · fundamental ·
  text · crossSection · portfolio · strategy 8 그룹)
- _ALIASES — 한글/영문 alias → 정식 축 이름
- _OLD_METRICS — 하위호환 metric 이름 set
- _GROUPS — 그룹 ID → 한국어 라벨
"""

from __future__ import annotations

from dataclasses import dataclass

# ── Axis Registry ────────────────────────────────────────


@dataclass(frozen=True)
class _AxisEntry:
    """quant 축 메타데이터."""

    module: str
    fn: str
    label: str
    description: str
    example: str
    group: str
    stockRequired: bool = True  # False = 횡단면/시장 레벨
    multiStock: bool = False  # True = 종목 리스트 입력


# ── A: 기술적 (technical) — 가격 전용 ────────────────────

_AXIS_REGISTRY: dict[str, _AxisEntry] = {
    "indicators": _AxisEntry(
        module="dartlab.quant.screen.axTechnical",
        fn="calcIndicators",
        label="지표",
        description="45개 기술적 지표 DataFrame (SMA, EMA, MACD, RSI, BB 등)",
        example='quant("지표", "005930")',
        group="technical",
    ),
    "signals": _AxisEntry(
        module="dartlab.quant.screen.axTechnical",
        fn="calcSignals",
        label="신호",
        description="최근 매매 신호 이벤트 (골든크로스, RSI, MACD, 볼린저)",
        example='quant("신호", "005930")',
        group="technical",
    ),
    "verdict": _AxisEntry(
        module="dartlab.quant.screen.axTechnical",
        fn="calcVerdict",
        label="판단",
        description="종합 기술적 판단 (강세/중립/약세) + RSI/SMA/BB",
        example='quant("판단", "005930")',
        group="technical",
    ),
    "momentum": _AxisEntry(
        module="dartlab.quant.signal.momentum",
        fn="calcMomentum",
        label="모멘텀",
        description="12-1개월 횡단면, 시계열 모멘텀, 52주 신고가 비율",
        example='quant("모멘텀", "005930")',
        group="technical",
    ),
    "volatility": _AxisEntry(
        module="dartlab.quant.risk.volatility",
        fn="calcVolatility",
        label="변동성",
        description="GARCH(1,1), HAR-RV 실현변동성, 변동성 기간구조 (forecast=True 면 horizon 일 후 변동성 + 분산 예측 추가)",
        example='quant("변동성", "005930")',
        group="technical",
    ),
    "forecast": _AxisEntry(
        module="dartlab.quant.benchmark.forecast",
        fn="forecastReturns",
        label="예측",
        description="일별 수익률 horizon-step 예측 + 90% Conformal interval (Naive·AR(1)·ETS-Holt·Theta 자동 dispatch)",
        example='quant("예측", "005930", horizon=5)',
        group="technical",
    ),
    "marketContext": _AxisEntry(
        module="dartlab.quant.regime.marketContext",
        fn="calcMarketContext",
        label="시장맥락",
        description="시장 베타 + 거시 민감도 (USDKRW/금리/CPI/M2) + 외국인+기관 수급 강도 1 행 evidence (price-level OLS, scan.macroBeta 와 책임 분리)",
        example='quant("시장맥락", "005930")',
        group="risk",
    ),
    "regime": _AxisEntry(
        module="dartlab.quant.regime.hmm",
        fn="calcRegime",
        label="레짐",
        description="Hamilton 2-state HMM (bull/bear), 추세추종 신호",
        example='quant("레짐", "005930")',
        group="technical",
    ),
    "pattern": _AxisEntry(
        module="dartlab.quant.regime.pattern",
        fn="calcPattern",
        label="패턴",
        description="캔들스틱 10종 + zigzag 기반 지지/저항",
        example='quant("패턴", "005930")',
        group="technical",
    ),
    "chartPatterns": _AxisEntry(
        module="dartlab.quant.regime.chartPatterns",
        fn="calcChartPatterns",
        label="차트패턴",
        description="거시 차트 패턴 — W/M/H&S/삼중/원형 (자동 인식 + 목표가)",
        example='quant("차트패턴", "005930")',
        group="technical",
    ),
    # ── B: 리스크 (risk) — 가격 + 벤치마크 ────────────────
    "beta": _AxisEntry(
        module="dartlab.quant.screen.axTechnical",
        fn="calcBeta",
        label="베타",
        description="시장/섹터/스타일 벤치마크 선택형 베타 + CAPM + 알파 + R²",
        example='quant("베타", "005930", benchmarkMode="sector")',
        group="risk",
    ),
    "benchmark": _AxisEntry(
        module="dartlab.quant.benchmark.data",
        fn="calcBenchmark",
        label="벤치마크",
        description="종목별 시장·섹터·스타일 KRX 벤치마크 스택과 기간 수익률",
        example='quant("벤치마크", "005930")',
        group="risk",
    ),
    "factor": _AxisEntry(
        module="dartlab.quant.factor.calc",
        fn="decomposeFactor",
        label="팩터",
        description="Fama-French 5 + q-factor 분해 (MKT/SMB/HML/RMW/CMA)",
        example='quant("팩터", "005930")',
        group="risk",
    ),
    "tailrisk": _AxisEntry(
        module="dartlab.quant.risk.tailrisk",
        fn="calcTailrisk",
        label="꼬리위험",
        description="CVaR, 최대낙폭, Sortino, 하방편차",
        example='quant("꼬리위험", "005930")',
        group="risk",
    ),
    "residual": _AxisEntry(
        module="dartlab.quant.factor.residual",
        fn="calcResidual",
        label="잔여수익",
        description="팩터 제거 후 잔여 모멘텀/알파",
        example='quant("잔여수익", "005930")',
        group="risk",
    ),
    # ── C: 미시구조 (microstructure) — 가격 + 거래량/수급 ─
    "liquidity": _AxisEntry(
        module="dartlab.quant.risk.microstructure",
        fn="calcLiquidity",
        label="유동성",
        description="Amihud 비유동성, Roll 스프레드, 회전율",
        example='quant("유동성", "005930")',
        group="microstructure",
    ),
    "flow": _AxisEntry(
        module="dartlab.quant.signal.flow",
        fn="calcFlow",
        label="수급",
        description="기관/외국인 매매 분석 (KR전용)",
        example='quant("수급", "005930")',
        group="microstructure",
    ),
    "volume": _AxisEntry(
        module="dartlab.quant.signal.volume",
        fn="calcVolume",
        label="거래량",
        description="OBV 추세, 거래량-가격 괴리, 누적분배",
        example='quant("거래량", "005930")',
        group="microstructure",
    ),
    # ── D: 펀더멘털 퀀트 (fundamental) — scan 프리빌드 ────
    "divergence": _AxisEntry(
        module="dartlab.quant.screen.axTechnical",
        fn="calcDivergence",
        label="괴리",
        description="재무-기술적 괴리 진단",
        example='quant("괴리", "005930")',
        group="fundamental",
    ),
    "quality": _AxisEntry(
        module="dartlab.quant.factor.quality",
        fn="calcQuality",
        label="퀄리티",
        description="Asness 퀄리티 팩터: 수익성+안전성+성장성 복합",
        example='quant("퀄리티", "005930")',
        group="fundamental",
    ),
    "value": _AxisEntry(
        module="dartlab.quant.factor.value",
        fn="calcValue",
        label="가치",
        description="가치 신호: PBR/PER/PSR vs 가격 모멘텀",
        example='quant("가치", "005930")',
        group="fundamental",
    ),
    "earnings": _AxisEntry(
        module="dartlab.quant.signal.earningsMomentum",
        fn="calcEarnings",
        label="이익모멘텀",
        description="SUE, PEAD, 이익 수정 모멘텀",
        example='quant("이익모멘텀", "005930")',
        group="fundamental",
    ),
    # ── E: 텍스트/공시 (text) — dartlab 고유 차별화 ───────
    "sentiment": _AxisEntry(
        module="dartlab.quant.text.sentiment",
        fn="calcSentiment",
        label="공시심리",
        description="Loughran-McDonald 감성 사전 기반 공시 텍스트 스코어링",
        example='quant("공시심리", "005930")',
        group="text",
    ),
    "toneChange": _AxisEntry(
        module="dartlab.quant.text.toneChange",
        fn="calcToneChange",
        label="톤변화",
        description="기간별 공시 톤 변화 감지",
        example='quant("톤변화", "005930")',
        group="text",
    ),
    "eventSignal": _AxisEntry(
        module="dartlab.quant.signal.event",
        fn="calcEventSignal",
        label="이벤트신호",
        description="allFilings 이벤트 기반 신호 (경영진변경, M&A 등)",
        example='quant("이벤트신호", "005930")',
        group="text",
    ),
    "riskText": _AxisEntry(
        module="dartlab.quant.text.risk",
        fn="calcRiskText",
        label="리스크텍스트",
        description="리스크 팩터 출현/소멸 텍스트 델타",
        example='quant("리스크텍스트", "005930")',
        group="text",
    ),
    "governanceQuant": _AxisEntry(
        module="dartlab.quant.text.governance",
        fn="calcGovernanceQuant",
        label="거버넌스퀀트",
        description="지배구조 품질 정량화 (사외이사비율, 감사의견, 보수)",
        example='quant("거버넌스퀀트", "005930")',
        group="text",
    ),
    # ── F: 횡단면 (crossSection) — 시장 레벨 ─────────────
    "ranking": _AxisEntry(
        module="dartlab.quant.factor.ranking",
        fn="calcRanking",
        label="순위",
        description="멀티팩터 복합 순위 (모멘텀+가치+퀄리티+리스크)",
        example='quant("순위")',
        group="crossSection",
        stockRequired=False,
    ),
    "pairs": _AxisEntry(
        module="dartlab.quant.signal.pairsTrading",
        fn="calcPairs",
        label="페어",
        description="공적분 기반 페어 트레이딩 후보 탐색",
        example='quant("페어")',
        group="crossSection",
        stockRequired=False,
    ),
    "screen": _AxisEntry(
        module="dartlab.quant.screen.preset",
        fn="calcScreen",
        label="스크린",
        description="팩터 스크리닝 프리셋 (가치/모멘텀/퀄리티/저변동)",
        example='quant("스크린")',
        group="crossSection",
        stockRequired=False,
    ),
    # ── Sprint 2 재무 알파 9축 (fundamental + risk) ─────────
    "altman": _AxisEntry(
        module="dartlab.quant.alphas.altman",
        fn="calcAltmanFactor",
        label="Altman Z",
        description="Altman 1968/1995 — 전종목 부실확률 (safe/grey/distress 3 zone) + topSafe/topDistress",
        example='quant("altman")',
        group="fundamental",
        stockRequired=False,
    ),
    "piotroski": _AxisEntry(
        module="dartlab.quant.alphas.piotroski",
        fn="calcPiotroskiFactor",
        label="Piotroski F",
        description="Piotroski 2000 — 9 신호 합 (0~9점) 전종목 분포 + 9 신호 시장 통과율",
        example='quant("piotroski")',
        group="fundamental",
        stockRequired=False,
    ),
    "beneish": _AxisEntry(
        module="dartlab.quant.alphas.beneish",
        fn="calcBeneishFactor",
        label="Beneish M",
        description="Beneish 1999 — 8변수 이익조작 감지, red flag (M > -1.78) 비율 + topFlag",
        example='quant("beneish")',
        group="fundamental",
        stockRequired=False,
    ),
    "accruals": _AxisEntry(
        module="dartlab.quant.alphas.accruals",
        fn="calcAccrualsFactor",
        label="Sloan Accrual",
        description="Sloan 1996 — (NI−CFO)/TA, high/neutral/low 3 그룹 분포",
        example='quant("accruals")',
        group="fundamental",
        stockRequired=False,
    ),
    "qfactor": _AxisEntry(
        module="dartlab.quant.alphas.qFactor",
        fn="calcQFactor",
        label="q-factor",
        description="Hou-Xue-Zhang 2015 — ROE + (−assetGrowth) composite, 수익성×보수투자",
        example='quant("qfactor")',
        group="fundamental",
        stockRequired=False,
    ),
    "qmj": _AxisEntry(
        module="dartlab.quant.alphas.qmj",
        fn="calcQMJ",
        label="QMJ",
        description="Asness-Frazzini-Pedersen 2019 — Profitability + Safety 합성 품질 랭킹",
        example='quant("qmj")',
        group="fundamental",
        stockRequired=False,
    ),
    "bab": _AxisEntry(
        module="dartlab.quant.alphas.bab",
        fn="calcBAB",
        label="BAB 저베타",
        description="Frazzini-Pedersen 2014 — 252일 beta 저베타 랭킹 + 60일 realized vol 보조",
        example='quant("bab")',
        group="risk",
        stockRequired=False,
    ),
    "surprise": _AxisEntry(
        module="dartlab.quant.alphas.earningsSurprise",
        fn="calcEarningsSurprise",
        label="이익서프라이즈",
        description="Bernard-Thomas 1989 PEAD — YoY NI growth z-score, positive SUE drift 후보",
        example='quant("surprise")',
        group="fundamental",
        stockRequired=False,
    ),
    "fundmom": _AxisEntry(
        module="dartlab.quant.alphas.fundamentalMomentum",
        fn="calcFundamentalMomentum",
        label="펀더-가격 모멘텀",
        description="Chordia-Shivakumar 2006 — earnings + 12-1 price 모멘텀 합성 랭킹",
        example='quant("fundmom")',
        group="fundamental",
        stockRequired=False,
    ),
    # ── G: 포트폴리오 (portfolio) — 멀티종목 ─────────────
    "meanvar": _AxisEntry(
        module="dartlab.quant.portfolio.optimize",
        fn="optimizeMeanVar",
        label="평균분산",
        description="Markowitz 평균-분산 최적화",
        example='quant("평균분산", ["005930","000660"])',
        group="portfolio",
        multiStock=True,
    ),
    "riskparity": _AxisEntry(
        module="dartlab.quant.portfolio.optimize",
        fn="optimizeRiskParity",
        label="리스크패리티",
        description="HRP (Lopez de Prado) 계층적 리스크 패리티",
        example='quant("리스크패리티", ["005930","000660"])',
        group="portfolio",
        multiStock=True,
    ),
    "allocation": _AxisEntry(
        module="dartlab.quant.portfolio.optimize",
        fn="allocateERC",
        label="자산배분",
        description="Equal Risk Contribution (Maillard 2010) — 종목별 위험 기여도 균등 배분",
        example='quant("자산배분", ["005930","000660"])',
        group="portfolio",
        multiStock=True,
    ),
    # ── H: Strategy DSL (사용자 컨트롤 boolean rule + 백테스트 + 검증) ────
    "strategy": _AxisEntry(
        module="dartlab.quant.screen.axStrategy",
        fn="runStrategy",
        label="전략",
        description="사용자 정의 boolean rule 백테스트 (Rule + sizing + stop)",
        example='quant("strategy", "005930", rule=myRule)',
        group="strategy",
    ),
    "backtest": _AxisEntry(
        module="dartlab.quant.screen.axStrategy",
        fn="runBacktest",
        label="백테스트",
        description="스타일명 또는 Rule 백테스트 (cpcv 옵션)",
        example='quant("backtest", "005930", style="trendFollow")',
        group="strategy",
    ),
    "style": _AxisEntry(
        module="dartlab.quant.screen.axStrategy",
        fn="runStyle",
        label="스타일",
        description="8 검증된 스타일 프리셋 일괄/단일 백테스트 (시총 의존 0)",
        example='quant("style", "005930", name="all")',
        group="strategy",
        stockRequired=False,  # name 없이 호출 시 카탈로그
    ),
    "entry": _AxisEntry(
        module="dartlab.quant.screen.axStrategy",
        fn="runEntry",
        label="진입진단",
        description="현재 시점 진입/청산/스톱 진단 (백테스트 안 돌림)",
        example='quant("entry", "005930", style="all")',
        group="strategy",
    ),
    "walkforward": _AxisEntry(
        module="dartlab.quant.screen.axStrategy",
        fn="runWalkforward",
        label="워크포워드",
        description="Lopez de Prado 슬라이딩 OOS Sharpe + DSR + PBO",
        example='quant("walkforward", "005930", style="meanReversion")',
        group="strategy",
    ),
    "multi": _AxisEntry(
        module="dartlab.quant.screen.axStrategy",
        fn="runMultiAsset",
        label="멀티자산",
        description="멀티 종목 포트폴리오 백테스트 (equal/inv_vol/risk_parity 가중)",
        example='quant("multi", ["005930","000660"], style="trendFollow")',
        group="strategy",
        multiStock=True,
    ),
}

# ── Alias 테이블 ─────────────────────────────────────────

_ALIASES: dict[str, str] = {
    # A: 기술적
    "지표": "indicators",
    "기술지표": "indicators",
    "신호": "signals",
    "매매신호": "signals",
    "판단": "verdict",
    "종합": "verdict",
    "종합판단": "verdict",
    "기술판단": "verdict",
    "모멘텀": "momentum",
    "추세": "momentum",
    "변동성": "volatility",
    "vol": "volatility",
    "예측": "forecast",
    "수익률예측": "forecast",
    "forecastReturns": "forecast",
    "returnsForecast": "forecast",
    "시장맥락": "marketContext",
    "맥락": "marketContext",
    "calcMarketContext": "marketContext",
    "레짐": "regime",
    "국면": "regime",
    "패턴": "pattern",
    "캔들": "pattern",
    "캔들패턴": "pattern",
    "차트패턴": "chartPatterns",
    "거시패턴": "chartPatterns",
    "쌍바닥": "chartPatterns",
    "쌍봉": "chartPatterns",
    "헤드앤숄더": "chartPatterns",
    # B: 리스크
    "베타": "beta",
    "시장베타": "beta",
    "벤치마크": "benchmark",
    "시장지수": "benchmark",
    "benchmarkIndex": "benchmark",
    "팩터": "factor",
    "팩터분해": "factor",
    "꼬리위험": "tailrisk",
    "테일리스크": "tailrisk",
    "CVaR": "tailrisk",
    "최대낙폭": "tailrisk",
    "잔여수익": "residual",
    "잔여모멘텀": "residual",
    "알파": "residual",
    # C: 미시구조
    "유동성": "liquidity",
    "비유동성": "liquidity",
    "수급": "flow",
    "외국인": "flow",
    "기관": "flow",
    "거래량": "volume",
    "OBV": "volume",
    # D: 펀더멘털 퀀트
    "괴리": "divergence",
    "재무괴리": "divergence",
    "퀄리티": "quality",
    "품질": "quality",
    "가치": "value",
    "밸류": "value",
    "valuation": "value",
    "valueFactor": "value",
    "이익모멘텀": "earnings",
    "SUE": "earnings",
    "PEAD": "earnings",
    # E: 텍스트/공시
    "공시심리": "sentiment",
    "감성": "sentiment",
    "톤변화": "toneChange",
    "이벤트신호": "eventSignal",
    "이벤트": "eventSignal",
    "리스크텍스트": "riskText",
    "거버넌스퀀트": "governanceQuant",
    "거버넌스": "governanceQuant",
    "지배구조": "governanceQuant",
    # F: 횡단면
    "순위": "ranking",
    "랭킹": "ranking",
    "페어": "pairs",
    "페어트레이딩": "pairs",
    "스크린": "screen",
    "스크리닝": "screen",
    "필터": "screen",
    # G: 포트폴리오
    "평균분산": "meanvar",
    "마코위츠": "meanvar",
    "리스크패리티": "riskparity",
    "HRP": "riskparity",
    "자산배분": "allocation",
    "ERC": "allocation",
    "리스크균등": "allocation",
    # H: Strategy DSL
    "전략": "strategy",
    "백테스트": "backtest",
    "스타일": "style",
    "진입": "entry",
    "진입진단": "entry",
    "워크포워드": "walkforward",
    "전진검증": "walkforward",
    "멀티자산": "multi",
    "포트폴리오백테스트": "multi",
    "multiasset": "multi",
    # Sprint 2 신규 alpha 한글 alias
    "알트만": "altman",
    "Altman": "altman",
    "부실": "altman",
    "Z스코어": "altman",
    "피오트로스키": "piotroski",
    "Piotroski": "piotroski",
    "F스코어": "piotroski",
    "재무건강": "piotroski",
    "베니쉬": "beneish",
    "Beneish": "beneish",
    "M스코어": "beneish",
    "이익조작": "beneish",
    "발생액": "accruals",
    "Sloan": "accruals",
    "발생액품질": "accruals",
    "q팩터": "qfactor",
    "Q팩터": "qfactor",
    "QMJ": "qmj",
    "품질마이너스쓰레기": "qmj",
    "BAB": "bab",
    "저변동성": "bab",
    "저변동": "bab",
    "서프라이즈": "surprise",
    "이익서프라이즈": "surprise",
    "earningsSurprise": "surprise",
    "펀더모멘텀": "fundmom",
    "fundamentalMomentum": "fundmom",
}

# 기존 metric 이름 (하위호환용)
_OLD_METRICS = {"indicators", "signals", "beta", "divergence", "flags", "verdict"}


_GROUPS = {
    "technical": "기술적",
    "risk": "리스크",
    "microstructure": "미시구조",
    "fundamental": "펀더멘털",
    "text": "텍스트/공시",
    "crossSection": "횡단면",
    "portfolio": "포트폴리오",
    "strategy": "전략 DSL",
}
