"""quant 엔진 스펙 — capability 라이브 빌더(builder.py) 자동 수집용."""

SPEC = {
    "engine": "quant",
    "layer": "L1",
    "description": "종목 레벨 정량분석 엔진. 기술적 지표부터 팩터 모델, 텍스트 감성, 포트폴리오 최적화까지.",
    "entrypoint": 'dartlab.quant("축명", "종목코드")',
    "groups": {
        "technical": {
            "label": "기술적",
            "description": "가격 데이터 기반 기술적 분석",
            "axes": ["indicators", "signals", "verdict", "momentum", "volatility", "regime", "pattern"],
        },
        "risk": {
            "label": "리스크",
            "description": "가격 + KRX 시장·섹터·스타일 벤치마크 기반 리스크 분석",
            "axes": ["beta", "benchmark", "factor", "tailrisk", "residual", "bab"],
        },
        "microstructure": {
            "label": "미시구조",
            "description": "거래량/수급 기반 시장 미시구조 분석",
            "axes": ["liquidity", "flow", "volume"],
        },
        "fundamental": {
            "label": "펀더멘털",
            "description": "재무제표 기반 정량 팩터",
            "axes": [
                "divergence",
                "quality",
                "value",
                "earnings",
                # Sprint 2 신규 (2026-04-25)
                "altman",
                "piotroski",
                "beneish",
                "accruals",
                "qfactor",
                "qmj",
                "surprise",
                "fundmom",
            ],
        },
        "text": {
            "label": "텍스트/공시",
            "description": "DART/EDGAR 공시 텍스트 기반 정량 신호 (dartlab 고유)",
            "axes": ["sentiment", "toneChange", "eventSignal", "riskText", "governanceQuant"],
        },
        "crossSection": {
            "label": "횡단면",
            "description": "시장 전체 횡단면 분석 (종목 불필요)",
            "axes": ["ranking", "pairs", "screen"],
        },
        "portfolio": {
            "label": "포트폴리오",
            "description": "멀티종목 포트폴리오 최적화",
            "axes": ["meanvar", "riskparity", "allocation"],
        },
    },
    "axes": {
        "indicators": {
            "label": "지표",
            "description": "45개 기술적 지표 (SMA, EMA, MACD, RSI, BB, ADX 등)",
            "when": "가격 추세/모멘텀/과매수과매도 상태 확인",
            "key_output": "25컬럼 DataFrame (OHLCV + 지표)",
        },
        "signals": {
            "label": "신호",
            "description": "9개 매매 신호 (골든크로스, RSI, MACD, 볼린저, 채널돌파)",
            "when": "매매 타이밍 판단",
            "key_output": "최근 20일 신호 이벤트 리스트",
        },
        "verdict": {
            "label": "판단",
            "description": "종합 기술적 판단 (강세/중립/약세)",
            "when": "한눈에 기술적 상태 확인",
            "key_output": "verdict, score(-4~+4), latestValues",
        },
        "momentum": {
            "label": "모멘텀",
            "description": "12-1개월 횡단면 모멘텀, 시계열 모멘텀, 52주 신고가 비율",
            "when": "추세 지속 여부 판단",
            "key_output": "momentum12_1, tsMomentum, highRatio52w, crashRisk",
            "method": "Jegadeesh-Titman(1993), Moskowitz(2012), George-Hwang(2004)",
        },
        "volatility": {
            "label": "변동성",
            "description": "GARCH(1,1) 조건부 분산, HAR-RV 실현변동성, 변동성 기간구조",
            "when": "변동성 예측 및 리스크 관리",
            "key_output": "garchVol, harRV, volTermStructure, volRegime",
            "method": "Bollerslev(1986), Corsi(2009)",
        },
        "regime": {
            "label": "레짐",
            "description": "Hamilton 2-state HMM (bull/bear) + 추세추종 신호",
            "when": "시장 국면 판별 및 전환점 감지",
            "key_output": "regime(bull/bear), probability, trendSignal",
            "method": "Hamilton(1989)",
        },
        "pattern": {
            "label": "패턴",
            "description": "캔들스틱 10종 + zigzag 기반 지지/저항",
            "when": "단기 반전/지속 패턴 감지",
            "key_output": "patterns[], supportLevels, resistanceLevels",
        },
        "beta": {
            "label": "베타",
            "description": "시장/섹터/스타일 벤치마크 선택형 베타 + CAPM + 알파 + R²",
            "when": "시장 또는 업종 대비 민감도 판단",
            "key_output": "beta, alpha, rSquared, capmExpectedReturn",
        },
        "benchmark": {
            "label": "벤치마크",
            "description": "종목별 시장·섹터·스타일 KRX benchmarkStack",
            "when": "beta/factor/residual/BAB의 상대 기준 확인",
            "key_output": "benchmarkUsed, benchmarkStack, return1m/3m/6m/1y",
        },
        "factor": {
            "label": "팩터",
            "description": "Fama-French 5팩터 + q-factor 분해",
            "when": "수익률 원천 분해",
            "key_output": "MKT/SMB/HML/RMW/CMA 로딩 + 알파",
            "method": "Fama-French(2015), Hou-Xue-Zhang(2015)",
        },
        "tailrisk": {
            "label": "꼬리위험",
            "description": "CVaR, 최대낙폭, Sortino, 하방편차",
            "when": "극단 손실 리스크 측정",
            "key_output": "cvar95, maxDrawdown, sortino, downsideDev",
            "method": "Artzner(1999)",
        },
        "residual": {
            "label": "잔여수익",
            "description": "팩터 제거 후 잔여 모멘텀/알파",
            "when": "순수 종목 고유 수익률 분석",
            "key_output": "residualMomentum, idiosyncraticVol, residualAlpha",
            "method": "Blitz-Huij-Martens(2011)",
        },
        "liquidity": {
            "label": "유동성",
            "description": "Amihud 비유동성, Roll 스프레드, 회전율",
            "when": "거래 비용 및 시장 영향 추정",
            "key_output": "amihud, rollSpread, turnover, liquidityGrade",
            "method": "Amihud(2002), Roll(1984)",
        },
        "flow": {
            "label": "수급",
            "description": "기관/외국인 매매 분석 (KR전용)",
            "when": "스마트머니 방향 파악",
            "key_output": "foreignNetBuy, instNetBuy, flowMomentum, streak",
        },
        "volume": {
            "label": "거래량",
            "description": "OBV 추세, 거래량-가격 괴리, 누적분배",
            "when": "가격 움직임의 거래량 확인",
            "key_output": "obvTrend, volumePriceDivergence, adLine",
        },
        "divergence": {
            "label": "괴리",
            "description": "재무-기술적 괴리 진단",
            "when": "재무건전성과 주가 방향 불일치 감지",
            "key_output": "financialGrade, technicalVerdict, diagnosis",
        },
        "quality": {
            "label": "퀄리티",
            "description": "Asness 퀄리티 팩터: 수익성+안전성+성장성 복합",
            "when": "종목의 펀더멘털 품질 평가",
            "key_output": "qualityScore, profitability, safety, growth, percentile",
            "method": "Asness-Frazzini-Pedersen(2019)",
        },
        "value": {
            "label": "가치",
            "description": "가치 신호: PBR/PER/PSR vs 가격 모멘텀",
            "when": "저평가/고평가 판단",
            "key_output": "valueScore, pbrPercentile, perPercentile, valueWithMomentum",
        },
        "earnings": {
            "label": "이익모멘텀",
            "description": "SUE, PEAD, 이익 수정 모멘텀",
            "when": "실적 서프라이즈 기반 투자 판단",
            "key_output": "sue, peadSignal, revisionMomentum",
            "method": "Ball-Brown(1968), Bernard-Thomas(1989)",
        },
        "sentiment": {
            "label": "공시심리",
            "description": "Loughran-McDonald 감성 사전 기반 공시 텍스트 스코어링",
            "when": "공시 텍스트의 긍부정 톤 정량 측정",
            "key_output": "sentimentScore, positiveRatio, negativeRatio, timeSeries",
            "method": "Loughran-McDonald(2011)",
        },
        "toneChange": {
            "label": "톤변화",
            "description": "기간별 공시 톤 변화 감지",
            "when": "공시 톤의 악화/개선 추적",
            "key_output": "toneShift, newNegatives, lostPositives, magnitude",
        },
        "eventSignal": {
            "label": "이벤트신호",
            "description": "allFilings 이벤트 기반 신호 (경영진변경, M&A, 유증 등)",
            "when": "중요 공시 이벤트 발생 시 신호",
            "key_output": "events[], impactScore, eventType",
        },
        "riskText": {
            "label": "리스크텍스트",
            "description": "리스크 팩터 출현/소멸 텍스트 델타",
            "when": "새로운 리스크 요인 등장 감지",
            "key_output": "newRisks[], removedRisks[], riskTrend",
        },
        "governanceQuant": {
            "label": "거버넌스퀀트",
            "description": "지배구조 품질 정량화",
            "when": "거버넌스 리스크 측정",
            "key_output": "governanceScore, boardIndependence, auditQuality, payRatio",
        },
        "ranking": {
            "label": "순위",
            "description": "멀티팩터 복합 순위",
            "when": "전종목 대상 투자 후보 선정",
            "key_output": "DataFrame(stockCode, compositeScore, rank)",
        },
        "pairs": {
            "label": "페어",
            "description": "공적분 기반 페어 트레이딩 후보 탐색",
            "when": "통계적 차익거래 기회 탐색",
            "key_output": "DataFrame(pair, cointegrationPValue, halfLife)",
            "method": "Engle-Granger(1987)",
        },
        "screen": {
            "label": "스크린",
            "description": "팩터 스크리닝 프리셋 (가치/모멘텀/퀄리티/저변동)",
            "when": "특정 투자 전략 기반 종목 필터링",
            "key_output": "DataFrame(stockCode, factorScores)",
        },
        "meanvar": {
            "label": "평균분산",
            "description": "Markowitz 평균-분산 최적화",
            "when": "최적 포트폴리오 가중치 산출",
            "key_output": "weights, expectedReturn, risk, sharpe",
            "method": "Markowitz(1952)",
        },
        "riskparity": {
            "label": "리스크패리티",
            "description": "HRP 계층적 리스크 패리티",
            "when": "안정적 리스크 배분 포트폴리오",
            "key_output": "weights, riskContribution, dendrogram",
            "method": "Lopez de Prado(2016)",
        },
        "allocation": {
            "label": "자산배분",
            "description": "Black-Litterman + 리스크 버짓팅",
            "when": "투자자 뷰 반영 자산배분",
            "key_output": "weights, posteriorReturns, riskBudget",
            "method": "Black-Litterman(1992)",
        },
        # ── Sprint 2 신규 9 alpha (2026-04-25) ─────────────────
        "altman": {
            "label": "Altman Z",
            "description": "전종목 Z-Score 부실확률 (1968 5변수 / 1995 Z'' 4변수)",
            "when": "시장 부실위험 분포 + topSafe/topDistress 종목 식별",
            "key_output": "scores, zones(safe/grey/distress), topSafe, topDistress",
            "method": "Altman(1968), Altman-Hotchkiss(2006)",
        },
        "piotroski": {
            "label": "Piotroski F",
            "description": "9 신호 합 (0~9점) 재무건강 횡단면 분포",
            "when": "재무건강 strong (F≥7) / weak (F≤3) 종목 식별",
            "key_output": "scores, grades(strong/moderate/weak), topStrong, signalAvg",
            "method": "Piotroski(2000)",
        },
        "beneish": {
            "label": "Beneish M",
            "description": "8변수 이익조작 감지 (DSRI/GMI/AQI/SGI/DEPI/SGAI/TATA/LVGI)",
            "when": "red flag (M > -1.78) 의심 종목 + clean 종목 식별",
            "key_output": "scores, flags(redFlag/clean), topFlag, topClean",
            "method": "Beneish(1999)",
        },
        "accruals": {
            "label": "Sloan Accrual",
            "description": "(NI − CFO) / TA 발생액품질 횡단면",
            "when": "high accrual (reversal risk) / low accrual (cash quality premium 후보) 식별",
            "key_output": "scores, groups(high/neutral/low), topHigh, topLow",
            "method": "Sloan(1996), Dechow-Dichev(2002)",
        },
        "qfactor": {
            "label": "q-factor",
            "description": "ROE + (−assetGrowth) percentile composite (수익성×보수투자)",
            "when": "Hou-Xue-Zhang q-premium 후보 식별",
            "key_output": "scores, components(roe, assetGrowth, ranks), topQ, bottomQ",
            "method": "Hou-Xue-Zhang(2015)",
        },
        "qmj": {
            "label": "QMJ",
            "description": "Profitability (ROE/ROA/CFOA) + Safety (-leverage) 합성 품질",
            "when": "Asness Quality minus Junk premium 후보 식별",
            "key_output": "scores, components, topQuality, topJunk",
            "method": "Asness-Frazzini-Pedersen(2019)",
        },
        "bab": {
            "label": "BAB 저베타",
            "description": "252일 OLS beta 저베타 랭킹 + 60일 realized vol 보조",
            "when": "Frazzini-Pedersen BAB long 후보 식별",
            "key_output": "scores(beta), topLow, topHigh, volScores, topLowVol",
            "method": "Frazzini-Pedersen(2014)",
        },
        "surprise": {
            "label": "이익서프라이즈",
            "description": "YoY NI growth 횡단면 z-score (PEAD drift 후보)",
            "when": "Bernard-Thomas PEAD long-short 후보 식별",
            "key_output": "scores(z), growths, topPos, topNeg",
            "method": "Bernard-Thomas(1989), Ball-Brown(1968)",
        },
        "fundmom": {
            "label": "펀더-가격 모멘텀",
            "description": "earnings growth + 12-1 price momentum 합성 (rank avg)",
            "when": "Chordia-Shivakumar 펀더멘털×가격 double-momentum long 후보",
            "key_output": "scores, components(earningsGrowth, priceMom12_1), topDouble",
            "method": "Chordia-Shivakumar(2006), Jegadeesh-Titman(1993)",
        },
    },
    "markets": ["KR", "US"],
    "dataSources": {
        "price": "Naver/Yahoo OHLCV (gather)",
        "flow": "Naver 기관/외국인 수급 (KR전용)",
        "scan": "전종목 재무제표 프리빌드 parquet",
        "docs": "DART/EDGAR 공시 텍스트",
        "changes": "공시 변화 델타 parquet",
    },
    "methods": {
        "Fama-French 5": "Fama-French(2015) — MKT/SMB/HML/RMW/CMA. numpy 회귀",
        "q-Factor": "Hou-Xue-Zhang(2015) — ROE + Investment. numpy 회귀",
        "GARCH(1,1)": "Bollerslev(1986) — 조건부 분산. numpy MLE",
        "HAR-RV": "Corsi(2009) — 실현변동성 예측. 일/주/월 분해",
        "HMM": "Hamilton(1989) — 2-state bull/bear. numpy EM + Kim smoother",
        "HRP": "Lopez de Prado(2016) — 계층적 리스크 패리티. numpy clustering",
        "Black-Litterman": "Black-Litterman(1992) — 베이지안 자산배분",
        "Amihud": "Amihud(2002) — 비유동성 비율. |수익률|/거래대금",
        "Engle-Granger": "Engle-Granger(1987) — 공적분 검정. numpy ADF",
        "Loughran-McDonald": "LM(2011) — 재무 텍스트 감성 사전",
        "Jegadeesh-Titman": "JT(1993) — 12-1개월 횡단면 모멘텀",
        "CVaR": "Artzner(1999) — 조건부 VaR (Expected Shortfall)",
    },
    "unique": "DART/EDGAR 공시 텍스트 기반 감성/톤변화/이벤트 분석 — 다른 플랫폼에 없는 차별화",
}
