/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as DashboardCodeRouteImport } from './routes/dashboard.$code'
import { Route as AnalysisCodeRouteImport } from './routes/analysis.$code'
import { Route as AnalysisCodeIndexRouteImport } from './routes/analysis.$code.index'
import { Route as AnalysisCodeViewerRouteImport } from './routes/analysis.$code.viewer'
import { Route as AnalysisCodeTerminalRouteImport } from './routes/analysis.$code.terminal'
import { Route as AnalysisCodeQuantRouteImport } from './routes/analysis.$code.quant'
import { Route as AnalysisCodeFinancialRouteImport } from './routes/analysis.$code.financial'
import { Route as AnalysisCodeEventsRouteImport } from './routes/analysis.$code.events'

const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const DashboardCodeRoute = DashboardCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => DashboardRoute,
} as any)
const AnalysisCodeRoute = AnalysisCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisCodeIndexRoute = AnalysisCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisCodeRoute,
} as any)
const AnalysisCodeViewerRoute = AnalysisCodeViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => AnalysisCodeRoute,
} as any)
const AnalysisCodeTerminalRoute = AnalysisCodeTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AnalysisCodeRoute,
} as any)
const AnalysisCodeQuantRoute = AnalysisCodeQuantRouteImport.update({
  id: '/quant',
  path: '/quant',
  getParentRoute: () => AnalysisCodeRoute,
} as any)
const AnalysisCodeFinancialRoute = AnalysisCodeFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AnalysisCodeRoute,
} as any)
const AnalysisCodeEventsRoute = AnalysisCodeEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AnalysisCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/analysis/$code': typeof AnalysisCodeRouteWithChildren
  '/dashboard/$code': typeof DashboardCodeRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/analysis/$code/events': typeof AnalysisCodeEventsRoute
  '/analysis/$code/financial': typeof AnalysisCodeFinancialRoute
  '/analysis/$code/quant': typeof AnalysisCodeQuantRoute
  '/analysis/$code/terminal': typeof AnalysisCodeTerminalRoute
  '/analysis/$code/viewer': typeof AnalysisCodeViewerRoute
  '/analysis/$code/': typeof AnalysisCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/screener': typeof ScreenerRoute
  '/dashboard/$code': typeof DashboardCodeRoute
  '/analysis': typeof AnalysisIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/analysis/$code/events': typeof AnalysisCodeEventsRoute
  '/analysis/$code/financial': typeof AnalysisCodeFinancialRoute
  '/analysis/$code/quant': typeof AnalysisCodeQuantRoute
  '/analysis/$code/terminal': typeof AnalysisCodeTerminalRoute
  '/analysis/$code/viewer': typeof AnalysisCodeViewerRoute
  '/analysis/$code': typeof AnalysisCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/analysis/$code': typeof AnalysisCodeRouteWithChildren
  '/dashboard/$code': typeof DashboardCodeRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/analysis/$code/events': typeof AnalysisCodeEventsRoute
  '/analysis/$code/financial': typeof AnalysisCodeFinancialRoute
  '/analysis/$code/quant': typeof AnalysisCodeQuantRoute
  '/analysis/$code/terminal': typeof AnalysisCodeTerminalRoute
  '/analysis/$code/viewer': typeof AnalysisCodeViewerRoute
  '/analysis/$code/': typeof AnalysisCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/ask'
    | '/dashboard'
    | '/screener'
    | '/analysis/$code'
    | '/dashboard/$code'
    | '/analysis/'
    | '/dashboard/'
    | '/analysis/$code/events'
    | '/analysis/$code/financial'
    | '/analysis/$code/quant'
    | '/analysis/$code/terminal'
    | '/analysis/$code/viewer'
    | '/analysis/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/screener'
    | '/dashboard/$code'
    | '/analysis'
    | '/dashboard'
    | '/analysis/$code/events'
    | '/analysis/$code/financial'
    | '/analysis/$code/quant'
    | '/analysis/$code/terminal'
    | '/analysis/$code/viewer'
    | '/analysis/$code'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/ask'
    | '/dashboard'
    | '/screener'
    | '/analysis/$code'
    | '/dashboard/$code'
    | '/analysis/'
    | '/dashboard/'
    | '/analysis/$code/events'
    | '/analysis/$code/financial'
    | '/analysis/$code/quant'
    | '/analysis/$code/terminal'
    | '/analysis/$code/viewer'
    | '/analysis/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  AskRoute: typeof AskRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ScreenerRoute: typeof ScreenerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/dashboard/$code': {
      id: '/dashboard/$code'
      path: '/$code'
      fullPath: '/dashboard/$code'
      preLoaderRoute: typeof DashboardCodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/analysis/$code': {
      id: '/analysis/$code'
      path: '/$code'
      fullPath: '/analysis/$code'
      preLoaderRoute: typeof AnalysisCodeRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/$code/': {
      id: '/analysis/$code/'
      path: '/'
      fullPath: '/analysis/$code/'
      preLoaderRoute: typeof AnalysisCodeIndexRouteImport
      parentRoute: typeof AnalysisCodeRoute
    }
    '/analysis/$code/viewer': {
      id: '/analysis/$code/viewer'
      path: '/viewer'
      fullPath: '/analysis/$code/viewer'
      preLoaderRoute: typeof AnalysisCodeViewerRouteImport
      parentRoute: typeof AnalysisCodeRoute
    }
    '/analysis/$code/terminal': {
      id: '/analysis/$code/terminal'
      path: '/terminal'
      fullPath: '/analysis/$code/terminal'
      preLoaderRoute: typeof AnalysisCodeTerminalRouteImport
      parentRoute: typeof AnalysisCodeRoute
    }
    '/analysis/$code/quant': {
      id: '/analysis/$code/quant'
      path: '/quant'
      fullPath: '/analysis/$code/quant'
      preLoaderRoute: typeof AnalysisCodeQuantRouteImport
      parentRoute: typeof AnalysisCodeRoute
    }
    '/analysis/$code/financial': {
      id: '/analysis/$code/financial'
      path: '/financial'
      fullPath: '/analysis/$code/financial'
      preLoaderRoute: typeof AnalysisCodeFinancialRouteImport
      parentRoute: typeof AnalysisCodeRoute
    }
    '/analysis/$code/events': {
      id: '/analysis/$code/events'
      path: '/events'
      fullPath: '/analysis/$code/events'
      preLoaderRoute: typeof AnalysisCodeEventsRouteImport
      parentRoute: typeof AnalysisCodeRoute
    }
  }
}

interface AnalysisCodeRouteChildren {
  AnalysisCodeEventsRoute: typeof AnalysisCodeEventsRoute
  AnalysisCodeFinancialRoute: typeof AnalysisCodeFinancialRoute
  AnalysisCodeQuantRoute: typeof AnalysisCodeQuantRoute
  AnalysisCodeTerminalRoute: typeof AnalysisCodeTerminalRoute
  AnalysisCodeViewerRoute: typeof AnalysisCodeViewerRoute
  AnalysisCodeIndexRoute: typeof AnalysisCodeIndexRoute
}

const AnalysisCodeRouteChildren: AnalysisCodeRouteChildren = {
  AnalysisCodeEventsRoute: AnalysisCodeEventsRoute,
  AnalysisCodeFinancialRoute: AnalysisCodeFinancialRoute,
  AnalysisCodeQuantRoute: AnalysisCodeQuantRoute,
  AnalysisCodeTerminalRoute: AnalysisCodeTerminalRoute,
  AnalysisCodeViewerRoute: AnalysisCodeViewerRoute,
  AnalysisCodeIndexRoute: AnalysisCodeIndexRoute,
}

const AnalysisCodeRouteWithChildren = AnalysisCodeRoute._addFileChildren(
  AnalysisCodeRouteChildren,
)

interface AnalysisRouteChildren {
  AnalysisCodeRoute: typeof AnalysisCodeRouteWithChildren
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisCodeRoute: AnalysisCodeRouteWithChildren,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCodeRoute: typeof DashboardCodeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCodeRoute: DashboardCodeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  AskRoute: AskRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ScreenerRoute: ScreenerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
