#!/usr/bin/env python3
"""Block generated-attribution markers in commit messages and staged content."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

BANNED_PATTERNS = [
    r"co-authored-by",
    r"generated by\s+(chatgpt|claude|codex|gpt|gemini|llm|ai)",
    r"ai assisted",
    r"ai-generated",
    r"ai generated",
    r"with claude",
    r"with chatgpt",
    r"with codex",
    r"gpt 협업",
]

COMPILED_PATTERNS = [re.compile(pattern, re.IGNORECASE) for pattern in BANNED_PATTERNS]
COMMIT_MESSAGE_BANNED_PATTERNS = [
    *BANNED_PATTERNS,
    r"\b(chatgpt|claude|codex|gpt|gemini|llm|ai)\b",
    r"생성\s*도구",
    r"작성\s*도구",
    r"모델\s*작성",
]
COMPILED_COMMIT_MESSAGE_PATTERNS = [re.compile(pattern, re.IGNORECASE) for pattern in COMMIT_MESSAGE_BANNED_PATTERNS]
COMMIT_TYPES = (
    "추가",
    "수정",
    "개선",
    "변경",
    "삭제",
    "정리",
    "문서",
    "테스트",
    "빌드",
    "릴리즈",
    "보안",
    "성능",
    "리팩터",
    "리팩토링",
    "복구",
    "설정",
    "검증",
)
GENERIC_COMMIT_DETAILS = {
    "작업",
    "수정",
    "변경",
    "업데이트",
    "정리",
    "개선",
    "추가",
    "삭제",
    "wip",
    "fix",
    "update",
    "changes",
}
HANGUL_RE = re.compile(r"[가-힣]")
ZERO_SHA = "0" * 40


def run_git(args: list[str], check: bool = True) -> str:
    proc = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout or ""


def find_matches(text: str) -> list[str]:
    if not text:
        return []
    matches: list[str] = []
    seen: set[str] = set()
    for pattern in COMPILED_PATTERNS:
        for match in pattern.finditer(text):
            snippet = match.group(0)
            key = snippet.lower()
            if key not in seen:
                seen.add(key)
                matches.append(snippet)
    return matches


def find_commit_message_matches(text: str) -> list[str]:
    if not text:
        return []
    matches: list[str] = []
    seen: set[str] = set()
    for pattern in COMPILED_COMMIT_MESSAGE_PATTERNS:
        for match in pattern.finditer(text):
            snippet = match.group(0)
            key = snippet.lower()
            if key not in seen:
                seen.add(key)
                matches.append(snippet)
    return matches


def report_failure(title: str, details: list[str]) -> int:
    print(f"[ai-policy] {title}", file=sys.stderr)
    for detail in details:
        print(f"  - {detail}", file=sys.stderr)
    return 1


def check_text(label: str, text: str) -> int:
    matches = find_matches(text)
    if not matches:
        return 0
    return report_failure(label, [f"금지 패턴 발견: {', '.join(matches)}"])


def check_commit_message(path: str) -> int:
    content = Path(path).read_text(encoding="utf-8", errors="replace")
    failures: list[str] = []
    matches = find_commit_message_matches(content)
    if matches:
        failures.append(f"금지 패턴 발견: {', '.join(matches)}")

    subject = next(
        (
            line.strip().lstrip("\ufeff")
            for line in content.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ),
        "",
    )
    if not subject:
        failures.append("커밋 제목이 비어 있습니다.")
    elif not HANGUL_RE.search(subject):
        failures.append("커밋 제목은 한글로 작성해야 합니다.")
    elif ":" not in subject:
        failures.append("커밋 제목은 '성격: 변경 내용' 형식이어야 합니다.")
    else:
        commit_type, detail = subject.split(":", 1)
        commit_type = commit_type.strip()
        detail = detail.strip()
        if commit_type not in COMMIT_TYPES:
            failures.append(f"커밋 성격은 다음 중 하나여야 합니다: {', '.join(COMMIT_TYPES)}")
        if not detail:
            failures.append("커밋 제목에 실제 변경 내용을 적어야 합니다.")
        elif len(detail) < 6 or detail.lower() in GENERIC_COMMIT_DETAILS:
            failures.append("커밋 제목의 변경 내용이 너무 짧거나 일반적입니다.")
        elif not HANGUL_RE.search(detail):
            failures.append("커밋 제목의 변경 내용은 한글 설명을 포함해야 합니다.")

    if not failures:
        return 0
    return report_failure("커밋 메시지 규칙을 위반했습니다.", failures)


def staged_files() -> list[str]:
    output = run_git(["diff", "--cached", "--name-only", "--diff-filter=ACMR"])
    return [line for line in output.splitlines() if line.strip()]


def check_staged() -> int:
    failures: list[str] = []
    for file_path in staged_files():
        if file_path == "scripts/audit/check_no_ai_markers.py":
            continue
        if Path(file_path).suffix.lower() == ".parquet":
            continue
        try:
            content = run_git(["show", f":{file_path}"])
        except RuntimeError:
            continue
        matches = find_matches(content)
        if matches:
            failures.append(f"{file_path}: {', '.join(matches)}")
    if not failures:
        return 0
    return report_failure("스테이징된 내용에 AI 흔적이 포함되어 있습니다.", failures)


def commit_range(base: str | None, head: str) -> list[str]:
    if base and base != ZERO_SHA:
        revspec = f"{base}..{head}"
        output = run_git(["rev-list", revspec])
        return [line for line in output.splitlines() if line.strip()]
    output = run_git(["rev-list", head, "--not", "--all"])
    commits = [line for line in output.splitlines() if line.strip()]
    return commits or [head]


def check_commit_range(base: str | None, head: str) -> int:
    failures: list[str] = []
    for commit in commit_range(base, head):
        message = run_git(["log", "--format=%B", "-n", "1", commit])
        matches = find_matches(message)
        if matches:
            failures.append(f"{commit[:12]}: {', '.join(matches)}")
    if not failures:
        return 0
    return report_failure("커밋 히스토리에 AI 기여자 흔적이 포함되어 있습니다.", failures)


def changed_files_in_range(base: str | None, head: str) -> list[str]:
    if base and base != ZERO_SHA:
        output = run_git(["diff", "--name-only", f"{base}..{head}", "--diff-filter=ACMR"])
        return [line for line in output.splitlines() if line.strip()]
    files: set[str] = set()
    for commit in commit_range(base, head):
        output = run_git(["diff-tree", "--no-commit-id", "--name-only", "-r", "--diff-filter=ACMR", commit])
        for line in output.splitlines():
            if line.strip():
                files.add(line)
    return sorted(files)


def check_files_in_range(base: str | None, head: str) -> int:
    failures: list[str] = []
    for file_path in changed_files_in_range(base, head):
        if file_path == "scripts/audit/check_no_ai_markers.py":
            continue
        if Path(file_path).suffix.lower() == ".parquet":
            continue
        if not Path(file_path).exists():
            continue
        try:
            content = Path(file_path).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        matches = find_matches(content)
        if matches:
            failures.append(f"{file_path}: {', '.join(matches)}")
    if not failures:
        return 0
    return report_failure("변경 파일 내용에 AI 흔적이 포함되어 있습니다.", failures)


def check_push() -> int:
    failures = 0
    for line in sys.stdin:
        local_ref, local_sha, _remote_ref, remote_sha = line.strip().split()
        if local_sha == ZERO_SHA:
            continue
        if check_commit_range(remote_sha, local_sha) != 0:
            failures = 1
        if check_files_in_range(remote_sha, local_sha) != 0:
            failures = 1
    return failures


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-commit-msg")
    parser.add_argument("--check-staged", action="store_true")
    parser.add_argument("--check-range", nargs=2, metavar=("BASE", "HEAD"))
    parser.add_argument("--check-push", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.check_commit_msg:
        return check_commit_message(args.check_commit_msg)
    if args.check_staged:
        return check_staged()
    if args.check_range:
        base, head = args.check_range
        commit_status = check_commit_range(base, head)
        file_status = check_files_in_range(base, head)
        return 1 if commit_status or file_status else 0
    if args.check_push:
        return check_push()
    print("No check mode provided.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
