#!/usr/bin/env python3
"""Block AI attribution markers in commit messages and staged content."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

BANNED_PATTERNS = [
    r"co-authored-by",
    r"generated by\s+(chatgpt|claude|codex|gpt|gemini|llm|ai)",
    r"ai assisted",
    r"ai-generated",
    r"ai generated",
    r"with claude",
    r"with chatgpt",
    r"with codex",
    r"gpt 협업",
]

COMPILED_PATTERNS = [re.compile(pattern, re.IGNORECASE) for pattern in BANNED_PATTERNS]
ZERO_SHA = "0" * 40


def run_git(args: list[str], check: bool = True) -> str:
    proc = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout or ""


def find_matches(text: str) -> list[str]:
    if not text:
        return []
    matches: list[str] = []
    seen: set[str] = set()
    for pattern in COMPILED_PATTERNS:
        for match in pattern.finditer(text):
            snippet = match.group(0)
            key = snippet.lower()
            if key not in seen:
                seen.add(key)
                matches.append(snippet)
    return matches


def report_failure(title: str, details: list[str]) -> int:
    print(f"[ai-policy] {title}", file=sys.stderr)
    for detail in details:
        print(f"  - {detail}", file=sys.stderr)
    return 1


def check_text(label: str, text: str) -> int:
    matches = find_matches(text)
    if not matches:
        return 0
    return report_failure(label, [f"금지 패턴 발견: {', '.join(matches)}"])


def check_commit_message(path: str) -> int:
    content = Path(path).read_text(encoding="utf-8", errors="replace")
    return check_text("커밋 메시지에 AI 흔적이 포함되어 있습니다.", content)


def staged_files() -> list[str]:
    output = run_git(["diff", "--cached", "--name-only", "--diff-filter=ACMR"])
    return [line for line in output.splitlines() if line.strip()]


def check_staged() -> int:
    failures: list[str] = []
    for file_path in staged_files():
        if file_path == "scripts/audit/check_no_ai_markers.py":
            continue
        if Path(file_path).suffix.lower() == ".parquet":
            continue
        try:
            content = run_git(["show", f":{file_path}"])
        except RuntimeError:
            continue
        matches = find_matches(content)
        if matches:
            failures.append(f"{file_path}: {', '.join(matches)}")
    if not failures:
        return 0
    return report_failure("스테이징된 내용에 AI 흔적이 포함되어 있습니다.", failures)


def commit_range(base: str | None, head: str) -> list[str]:
    if base and base != ZERO_SHA:
        revspec = f"{base}..{head}"
        output = run_git(["rev-list", revspec])
        return [line for line in output.splitlines() if line.strip()]
    output = run_git(["rev-list", head, "--not", "--all"])
    commits = [line for line in output.splitlines() if line.strip()]
    return commits or [head]


def check_commit_range(base: str | None, head: str) -> int:
    failures: list[str] = []
    for commit in commit_range(base, head):
        message = run_git(["log", "--format=%B", "-n", "1", commit])
        matches = find_matches(message)
        if matches:
            failures.append(f"{commit[:12]}: {', '.join(matches)}")
    if not failures:
        return 0
    return report_failure("커밋 히스토리에 AI 기여자 흔적이 포함되어 있습니다.", failures)


def changed_files_in_range(base: str | None, head: str) -> list[str]:
    if base and base != ZERO_SHA:
        output = run_git(["diff", "--name-only", f"{base}..{head}", "--diff-filter=ACMR"])
        return [line for line in output.splitlines() if line.strip()]
    files: set[str] = set()
    for commit in commit_range(base, head):
        output = run_git(["diff-tree", "--no-commit-id", "--name-only", "-r", "--diff-filter=ACMR", commit])
        for line in output.splitlines():
            if line.strip():
                files.add(line)
    return sorted(files)


def check_files_in_range(base: str | None, head: str) -> int:
    failures: list[str] = []
    for file_path in changed_files_in_range(base, head):
        if file_path == "scripts/audit/check_no_ai_markers.py":
            continue
        if Path(file_path).suffix.lower() == ".parquet":
            continue
        if not Path(file_path).exists():
            continue
        try:
            content = Path(file_path).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        matches = find_matches(content)
        if matches:
            failures.append(f"{file_path}: {', '.join(matches)}")
    if not failures:
        return 0
    return report_failure("변경 파일 내용에 AI 흔적이 포함되어 있습니다.", failures)


def check_push() -> int:
    failures = 0
    for line in sys.stdin:
        local_ref, local_sha, _remote_ref, remote_sha = line.strip().split()
        if local_sha == ZERO_SHA:
            continue
        if check_commit_range(remote_sha, local_sha) != 0:
            failures = 1
        if check_files_in_range(remote_sha, local_sha) != 0:
            failures = 1
    return failures


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-commit-msg")
    parser.add_argument("--check-staged", action="store_true")
    parser.add_argument("--check-range", nargs=2, metavar=("BASE", "HEAD"))
    parser.add_argument("--check-push", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.check_commit_msg:
        return check_commit_message(args.check_commit_msg)
    if args.check_staged:
        return check_staged()
    if args.check_range:
        base, head = args.check_range
        commit_status = check_commit_range(base, head)
        file_status = check_files_in_range(base, head)
        return 1 if commit_status or file_status else 0
    if args.check_push:
        return check_push()
    print("No check mode provided.", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
