"""DataEntry — report 카테고리 진입점 (Cut 8 분할).

단일 진실의 원천은 list 자체. 로직은 ``core/registry.py``.
"""

from __future__ import annotations

from dartlab.core.dataEntry import ColumnMeta, DataEntry  # noqa: F401

_REPORT_ENTRIES: list[DataEntry] = [
    # ═══════════════════════════════════════════════════════
    # report — 재무제표 (finance XBRL 우선, docs fallback)
    # ═══════════════════════════════════════════════════════
    DataEntry(
        name="BS",
        label="재무상태표",
        category="report",
        dataType="dataframe",
        description="K-IFRS 연결 재무상태표. finance XBRL 정규화(snakeId) 기반, 회사간 비교 가능. finance 없으면 docs fallback.",
        modulePath="dartlab.providers.dart.docs.finance.statements",
        funcName="statements",
        extractor=None,
        requires="finance",
        unit="원",
        columns=(ColumnMeta("항목", "K-IFRS 재무상태표 계정과목 (snakeId → 한글명)"),),
        analysisHints=(
            "부채비율(부채총계/자본총계) 추이",
            "유동비율(유동자산/유동부채) 확인",
            "자산 구성 변화 (유형 vs 무형 비중)",
            "IFRS 16 리스부채 영향 고려",
        ),
        relatedModules=("IS", "CF", "fsSummary"),
        maxRows=50,
    ),
    DataEntry(
        name="IS",
        label="손익계산서",
        category="report",
        dataType="dataframe",
        description="K-IFRS 연결 손익계산서. finance XBRL 정규화 기반. 매출액, 영업이익, 순이익 등 전체 계정 포함.",
        modulePath="dartlab.providers.dart.docs.finance.statements",
        funcName="statements",
        extractor=None,
        requires="finance",
        unit="원",
        columns=(ColumnMeta("항목", "K-IFRS 손익계산서 계정과목 (snakeId → 한글명)"),),
        analysisHints=(
            "매출 성장률(YoY) 계산",
            "영업이익률(영업이익/매출액) 추이",
            "순이익률(당기순이익/매출액) 추이",
            "매출원가율 변동 확인",
        ),
        relatedModules=("BS", "CF", "fsSummary", "segments"),
        maxRows=50,
    ),
    DataEntry(
        name="CF",
        label="현금흐름표",
        category="report",
        dataType="dataframe",
        description="K-IFRS 연결 현금흐름표. finance XBRL 정규화 기반. 영업/투자/재무활동 현금흐름.",
        modulePath="dartlab.providers.dart.docs.finance.statements",
        funcName="statements",
        extractor=None,
        requires="finance",
        unit="원",
        columns=(ColumnMeta("항목", "K-IFRS 현금흐름표 계정과목 (snakeId → 한글명)"),),
        analysisHints=(
            "영업활동CF가 양수인지 확인 (음수 = 위험)",
            "FCF = 영업활동CF - 자본적지출",
            "재무활동CF로 차입/상환 패턴 파악",
            "영업CF > 순이익이면 이익의 질 양호",
        ),
        relatedModules=("BS", "IS"),
        maxRows=50,
    ),
    DataEntry(
        name="fsSummary",
        label="요약재무정보",
        category="report",
        dataType="dataframe",
        description="DART 공시 요약재무정보. 다년간 주요 재무지표 비교.",
        modulePath="dartlab.providers.dart.docs.finance.summary",
        funcName="fsSummary",
        extractor=None,
        requires="docs",
        analysisHints=("전체 재무 추세의 출발점으로 활용",),
        relatedModules=("BS", "IS", "CF"),
        maxRows=50,
    ),
    DataEntry(
        name="segments",
        label="부문정보",
        category="report",
        dataType="dataframe",
        description="사업부문별 매출·이익 데이터. 부문간 수익성 비교 가능.",
        modulePath="dartlab.providers.dart.docs.finance.segment",
        funcName="segments",
        extractor=lambda r: r.revenue,
        requires="docs",
        analysisHints=(
            "부문별 매출 비중과 성장률",
            "부문별 수익성 차이와 성장 기여도",
        ),
        relatedModules=("IS", "productService"),
        aiQuestionTypes=("수익성", "성장성", "사업", "종합"),
        aiKeywords=("부문", "세그먼트", "segment"),
    ),
    DataEntry(
        name="tangibleAsset",
        label="유형자산",
        category="report",
        dataType="dataframe",
        description="유형자산 변동표. 취득/처분/감가상각 내역.",
        modulePath="dartlab.providers.dart.docs.finance.tangibleAsset",
        funcName="tangibleAsset",
        extractor=lambda r: r.movementDf,
        requires="docs",
        analysisHints=(
            "CAPEX 수준과 감가상각 비교",
            "자산 처분 규모 확인",
        ),
        relatedModules=("CF", "BS"),
        aiQuestionTypes=("투자",),
        aiKeywords=("유형자산", "설비"),
    ),
    DataEntry(
        name="costByNature",
        label="비용성격별분류",
        category="report",
        dataType="dataframe",
        description="비용을 성격별로 분류한 시계열. 원재료비, 인건비, 감가상각비 등.",
        modulePath="dartlab.providers.dart.docs.finance.costByNature",
        funcName="costByNature",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        analysisHints=(
            "비용 구조 변화 추적 (인건비 비중 등)",
            "원재료비 변동이 매출원가율에 미치는 영향",
        ),
        relatedModules=("IS", "rawMaterial"),
        aiQuestionTypes=("수익성",),
        aiKeywords=("원재료",),
    ),
    # ── 정기보고서 — 재무 관련 ──
    DataEntry(
        name="dividend",
        label="배당",
        category="report",
        dataType="dataframe",
        description="배당 시계열. 연도별 DPS, 배당총액, 배당성향, 배당수익률.",
        modulePath="dartlab.providers.dart.docs.finance.dividend",
        funcName="dividend",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        unit="원 (DPS), 백만원 (총액), % (배당성향·수익률)",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("netIncome", "당기순이익", "백만원"),
            ColumnMeta("eps", "주당순이익", "원"),
            ColumnMeta("totalDividend", "현금배당금총액", "백만원"),
            ColumnMeta("payoutRatio", "현금배당성향", "%"),
            ColumnMeta("dividendYield", "현금배당수익률", "%"),
            ColumnMeta("dps", "보통주 주당현금배당금", "원"),
        ),
        analysisHints=(
            "DPS 증감 추이 확인",
            "배당성향(DPS/EPS) 안정성 — 100% 초과 시 과배당 우려",
            "배당수익률 변화",
        ),
        relatedModules=("IS", "shareCapital"),
        aiQuestionTypes=("배당", "종합"),
        aiKeywords=("배당", "dividend"),
    ),
    DataEntry(
        name="majorHolder",
        label="최대주주",
        category="report",
        dataType="dataframe",
        description="최대주주 지분율 시계열. 지분 변동은 경영권 안정성의 핵심 지표.",
        modulePath="dartlab.providers.dart.docs.finance.majorHolder",
        funcName="majorHolder",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        unit="% (지분율), 주 (주식수)",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("majorHolder", "최대주주명"),
            ColumnMeta("majorRatio", "최대주주 지분율", "%"),
            ColumnMeta("totalRatio", "특수관계인 포함 총 지분율", "%"),
            ColumnMeta("holderCount", "주요주주 수", "명"),
        ),
        analysisHints=(
            "최대주주 지분율 변동 확인",
            "특수관계인 포함 총 지분율 30% 이상이면 경영권 안정",
        ),
        relatedModules=("holderOverview", "executive"),
        aiQuestionTypes=("지배구조", "종합"),
        aiKeywords=("주주",),
    ),
    DataEntry(
        name="employee",
        label="직원현황",
        category="report",
        dataType="dataframe",
        description="직원 수, 평균 근속연수, 평균 연봉 시계열.",
        modulePath="dartlab.providers.dart.docs.finance.employee",
        funcName="employee",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        unit="명 (인원), 년 (근속), 백만원 (연봉)",
        analysisHints=(
            "직원 수 증감과 매출 성장의 관계",
            "평균 연봉 수준 및 변화",
        ),
        relatedModules=("IS", "executivePay"),
        aiQuestionTypes=("인력", "종합"),
        aiKeywords=("직원", "employee"),
    ),
    DataEntry(
        name="subsidiary",
        label="자회사투자",
        category="report",
        dataType="dataframe",
        description="종속회사 투자 시계열. 지분율, 장부가액 변동.",
        modulePath="dartlab.providers.dart.docs.finance.subsidiary",
        funcName="subsidiary",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        unit="백만원 (금액), % (지분율)",
        analysisHints=(
            "자회사 손익이 연결 실적에 미치는 영향",
            "주요 자회사 지분율 변동",
        ),
        relatedModules=("investmentInOther", "affiliateGroup"),
        aiQuestionTypes=("성장성", "투자", "관계사"),
        aiKeywords=("자회사", "subsidiary"),
    ),
    DataEntry(
        name="bond",
        label="채무증권",
        category="report",
        dataType="dataframe",
        description="사채, CP 등 채무증권 발행·상환 시계열.",
        modulePath="dartlab.providers.dart.docs.finance.bond",
        funcName="bond",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        analysisHints=(
            "만기 도래 시점의 차환 리스크",
            "이자율 수준과 신용등급 연계",
        ),
        relatedModules=("BS", "CF", "contingentLiability"),
        aiKeywords=("채무증권", "사채"),
    ),
    DataEntry(
        name="shareCapital",
        label="주식현황",
        category="report",
        dataType="dataframe",
        description="발행주식수, 자기주식, 유통주식수 시계열.",
        modulePath="dartlab.providers.dart.docs.finance.shareCapital",
        funcName="shareCapital",
        extractor=lambda r: r.timeSeries,
        requires="docs",
        unit="주",
        analysisHints=(
            "자기주식 비율과 소각 여부",
            "유통주식수 변동이 주가에 미치는 영향",
        ),
        relatedModules=("capitalChange", "fundraising", "dividend"),
        aiQuestionTypes=("배당", "자본"),
        aiKeywords=("주식", "자기주식"),
    ),
    DataEntry(
        name="executive",
        label="임원현황",
        category="report",
        dataType="dataframe",
        description="등기임원 구성 시계열. 사내이사/사외이사/비상무이사 구분.",
        modulePath="dartlab.providers.dart.docs.finance.executive",
        funcName="executive",
        extractor=lambda r: r.executiveDf,
        requires="docs",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("totalRegistered", "등기임원 총원", "명"),
            ColumnMeta("insideDirectors", "사내이사", "명"),
            ColumnMeta("outsideDirectors", "사외이사", "명"),
            ColumnMeta("otherNonexec", "기타비상무이사", "명"),
            ColumnMeta("maleCount", "남성 임원", "명"),
            ColumnMeta("femaleCount", "여성 임원", "명"),
        ),
        analysisHints=("사외이사 비율 1/3 이상은 법적 요건",),
        relatedModules=("boardOfDirectors", "executivePay"),
        aiQuestionTypes=("지배구조",),
        aiKeywords=("임원",),
    ),
    DataEntry(
        name="executivePay",
        label="임원보수",
        category="report",
        dataType="dataframe",
        description="임원 유형별 보수 시계열. 등기이사/사외이사/감사 구분.",
        modulePath="dartlab.providers.dart.docs.finance.executivePay",
        funcName="executivePay",
        extractor=lambda r: r.payByTypeDf,
        requires="docs",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("category", "임원 유형"),
            ColumnMeta("headcount", "인원수", "명"),
            ColumnMeta("totalPay", "보수총액", "백만원"),
            ColumnMeta("avgPay", "1인당 평균보수", "백만원"),
        ),
        analysisHints=("평균 보수 대비 실적 적정성 판단",),
        relatedModules=("executive", "employee"),
        aiQuestionTypes=("지배구조", "인력"),
        aiKeywords=("보수", "급여", "employee"),
    ),
    DataEntry(
        name="audit",
        label="감사의견",
        category="report",
        dataType="dataframe",
        description="외부감사인의 감사의견과 감사보수 시계열. 적정 외 의견은 중대 위험 신호.",
        modulePath="dartlab.providers.dart.docs.finance.audit",
        funcName="audit",
        extractor=lambda r: r.opinionDf,
        apiType="auditOpinion",
        requires="docs",
        unit="백만원 (보수)",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("auditor", "감사인 (회계법인)"),
            ColumnMeta("opinion", "감사의견 (적정/한정/부적정/의견거절)"),
            ColumnMeta("keyAuditMatters", "핵심감사사항"),
        ),
        analysisHints=(
            "적정 외 의견은 중대 리스크 신호",
            "감사인 교체 빈번 여부 확인",
            "핵심감사사항의 반복 패턴",
        ),
        relatedModules=("auditSystem", "internalControl"),
        aiQuestionTypes=("건전성", "종합"),
        aiKeywords=("감사", "audit"),
    ),
    DataEntry(
        name="boardOfDirectors",
        label="이사회",
        category="report",
        dataType="dataframe",
        description="이사회 구성 및 활동 시계열. 개최횟수, 출석률 포함.",
        modulePath="dartlab.providers.dart.docs.finance.boardOfDirectors",
        funcName="boardOfDirectors",
        extractor=lambda r: r.boardDf,
        requires="docs",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("totalDirectors", "이사 총원", "명"),
            ColumnMeta("outsideDirectors", "사외이사", "명"),
            ColumnMeta("meetingCount", "이사회 개최횟수", "회"),
            ColumnMeta("avgAttendanceRate", "평균 출석률", "%"),
        ),
        analysisHints=("이사회 활동성(개최횟수)과 출석률 확인",),
        relatedModules=("executive", "auditSystem"),
        aiQuestionTypes=("지배구조", "인력"),
        aiKeywords=("이사회", "사외이사"),
    ),
    DataEntry(
        name="capitalChange",
        label="자본변동",
        category="report",
        dataType="dataframe",
        description="자본금 변동 시계열. 보통주/우선주 주식수·액면 변동.",
        modulePath="dartlab.providers.dart.docs.finance.capitalChange",
        funcName="capitalChange",
        extractor=lambda r: r.capitalDf,
        requires="docs",
        unit="주 (주식수), 원 (액면)",
        analysisHints=("증자/감자 이벤트와 지분 희석 효과",),
        relatedModules=("shareCapital", "fundraising"),
        aiQuestionTypes=("배당", "자본"),
        aiKeywords=("증자", "감자", "주식"),
    ),
    DataEntry(
        name="contingentLiability",
        label="우발부채",
        category="report",
        dataType="dataframe",
        description="채무보증, 소송 현황. 잠재적 재무 리스크 지표.",
        modulePath="dartlab.providers.dart.docs.finance.contingentLiability",
        funcName="contingentLiability",
        extractor=lambda r: r.guaranteeDf,
        requires="docs",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("totalGuaranteeAmount", "채무보증 총액", "백만원"),
            ColumnMeta("lineCount", "보증 건수", "건"),
        ),
        analysisHints=(
            "채무보증 총액 대비 자기자본 비율",
            "소송 규모와 진행 상태",
        ),
        relatedModules=("BS", "sanction"),
        aiQuestionTypes=("건전성", "리스크"),
        aiKeywords=("소송", "보증"),
    ),
    DataEntry(
        name="internalControl",
        label="내부통제",
        category="report",
        dataType="dataframe",
        description="내부회계관리제도 감사의견 시계열.",
        modulePath="dartlab.providers.dart.docs.finance.internalControl",
        funcName="internalControl",
        extractor=lambda r: r.controlDf,
        requires="docs",
        analysisHints=("내부통제 취약점은 재무제표 신뢰성 리스크",),
        relatedModules=("audit", "auditSystem"),
        aiQuestionTypes=("건전성",),
        aiKeywords=("내부통제",),
    ),
    DataEntry(
        name="relatedPartyTx",
        label="관계자거래",
        category="report",
        dataType="dataframe",
        description="대주주 등과의 매출·매입 거래 시계열. 이전가격 리스크 확인.",
        modulePath="dartlab.providers.dart.docs.finance.relatedPartyTx",
        funcName="relatedPartyTx",
        extractor=lambda r: r.revenueTxDf,
        requires="docs",
        analysisHints=("관계자 거래 비중이 매출의 10%+ 이면 주의",),
        relatedModules=("affiliateGroup", "majorHolder"),
        aiQuestionTypes=("건전성", "리스크", "관계사"),
    ),
    DataEntry(
        name="rnd",
        label="R&D",
        category="report",
        dataType="dataframe",
        description="연구개발비용 시계열. 기술 투자 강도 판단.",
        modulePath="dartlab.providers.dart.docs.finance.rnd",
        funcName="rnd",
        extractor=lambda r: r.rndDf,
        requires="docs",
        columns=(
            ColumnMeta("year", "사업연도"),
            ColumnMeta("rndExpense", "연구개발비", "백만원"),
            ColumnMeta("revenueRatio", "매출 대비 R&D 비율", "%"),
        ),
        analysisHints=(
            "매출 대비 R&D 비율의 업종 적정성",
            "R&D 투자 추세와 매출 성장의 관계",
        ),
        relatedModules=("IS", "productService"),
        aiQuestionTypes=("성장성", "투자", "종합"),
        aiKeywords=("연구", "연구개발", "R&D", "기술"),
    ),
    DataEntry(
        name="sanction",
        label="제재현황",
        category="report",
        dataType="dataframe",
        description="행정제재, 과징금, 영업정지 등 규제 조치 이력.",
        modulePath="dartlab.providers.dart.docs.finance.sanction",
        funcName="sanction",
        extractor=lambda r: r.sanctionDf,
        requires="docs",
        analysisHints=("제재 이력은 규제 리스크 신호", "반복 제재 패턴 확인"),
        relatedModules=("contingentLiability",),
        aiQuestionTypes=("리스크",),
        aiKeywords=("제재",),
    ),
    DataEntry(
        name="affiliateGroup",
        label="계열사",
        category="report",
        dataType="dataframe",
        description="기업집단 소속 계열회사 현황. 상장/비상장 구분.",
        modulePath="dartlab.providers.dart.docs.finance.affiliateGroup",
        funcName="affiliateGroup",
        extractor=lambda r: r.affiliateDf,
        requires="docs",
        analysisHints=("그룹 규모와 계열사 변동 추적",),
        relatedModules=("relatedPartyTx", "subsidiary"),
        maxRows=15,
        aiQuestionTypes=("리스크", "관계사", "지배구조"),
        aiKeywords=("계열사", "계열"),
    ),
    DataEntry(
        name="fundraising",
        label="증자감자",
        category="report",
        dataType="dataframe",
        description="유상증자, 무상증자, 감자 이력.",
        modulePath="dartlab.providers.dart.docs.finance.fundraising",
        funcName="fundraising",
        extractor=lambda r: r.issuanceDf,
        requires="docs",
        analysisHints=("증자 빈도와 목적 (시설/운영/차환)", "감자 이유 확인"),
        relatedModules=("capitalChange", "shareCapital"),
        aiQuestionTypes=("투자", "자본"),
        aiKeywords=("증자", "감자"),
    ),
    DataEntry(
        name="productService",
        label="주요제품",
        category="report",
        dataType="dataframe",
        description="주요 제품/서비스별 매출액과 비중.",
        modulePath="dartlab.providers.dart.docs.finance.productService",
        funcName="productService",
        extractor=lambda r: r.productDf,
        requires="docs",
        analysisHints=("매출 집중도(단일 제품 의존도) 확인",),
        relatedModules=("segments", "salesOrder"),
        aiQuestionTypes=("수익성", "성장성", "사업"),
        aiKeywords=("제품",),
    ),
    DataEntry(
        name="salesOrder",
        label="매출수주",
        category="report",
        dataType="dataframe",
        description="매출실적 및 수주 현황.",
        modulePath="dartlab.providers.dart.docs.finance.salesOrder",
        funcName="salesOrder",
        extractor=lambda r: r.salesDf,
        requires="docs",
        analysisHints=("수주잔고 추이로 미래 매출 가시성 확인",),
        relatedModules=("IS", "productService"),
        aiQuestionTypes=("수익성", "성장성", "사업"),
        aiKeywords=("수주",),
    ),
    DataEntry(
        name="riskDerivative",
        label="위험관리",
        category="report",
        dataType="dataframe",
        description="환율·이자율·상품가격 리스크 관리. 파생상품 보유 현황.",
        modulePath="dartlab.providers.dart.docs.finance.riskDerivative",
        funcName="riskDerivative",
        extractor=lambda r: r.fxDf,
        requires="docs",
        analysisHints=(
            "환위험 노출 규모와 헤지 비율",
            "파생상품 평가손익 추이",
        ),
        relatedModules=("IS", "BS"),
        aiQuestionTypes=("리스크",),
        aiKeywords=("파생", "환율", "환위험"),
    ),
    DataEntry(
        name="articlesOfIncorporation",
        label="정관",
        category="report",
        dataType="dataframe",
        description="정관 변경 이력. 사업목적 추가·변경으로 신사업 진출 파악.",
        modulePath="dartlab.providers.dart.docs.finance.articlesOfIncorporation",
        funcName="articlesOfIncorporation",
        extractor=lambda r: r.changesDf,
        requires="docs",
        analysisHints=("사업목적 추가/변경 사항 확인",),
        aiKeywords=("정관",),
    ),
    DataEntry(
        name="otherFinance",
        label="기타재무",
        category="report",
        dataType="dataframe",
        description="대손충당금, 재고자산 관련 기타 재무 데이터.",
        modulePath="dartlab.providers.dart.docs.finance.otherFinance",
        funcName="otherFinance",
        extractor=lambda r: r.badDebtDf,
        requires="docs",
        analysisHints=("대손충당금 적립률 추이", "재고자산 회전율 변동"),
        relatedModules=("BS", "IS"),
        aiKeywords=("대손", "재고"),
    ),
    DataEntry(
        name="companyHistory",
        label="연혁",
        category="report",
        dataType="dataframe",
        description="회사 주요 연혁 이벤트 목록.",
        modulePath="dartlab.providers.dart.docs.finance.companyHistory",
        funcName="companyHistory",
        extractor=lambda r: r.eventsDf,
        requires="docs",
        analysisHints=("최근 M&A, 사업 전환, 상장 등 주요 이벤트",),
        maxRows=20,
        aiQuestionTypes=("사업",),
        aiKeywords=("연혁",),
    ),
    DataEntry(
        name="shareholderMeeting",
        label="주주총회",
        category="report",
        dataType="dataframe",
        description="주주총회 안건 및 의결 결과.",
        modulePath="dartlab.providers.dart.docs.finance.shareholderMeeting",
        funcName="shareholderMeeting",
        extractor=lambda r: r.agendaDf,
        requires="docs",
        analysisHints=("안건 부결 여부, 특수 안건 확인",),
        relatedModules=("majorHolder",),
        aiQuestionTypes=("지배구조",),
        aiKeywords=("주총",),
    ),
    DataEntry(
        name="auditSystem",
        label="감사제도",
        category="report",
        dataType="dataframe",
        description="감사위원회 구성 및 활동 현황.",
        modulePath="dartlab.providers.dart.docs.finance.auditSystem",
        funcName="auditSystem",
        extractor=lambda r: r.committeeDf,
        requires="docs",
        analysisHints=("감사위원회 전원 사외이사 여부 확인",),
        relatedModules=("audit", "boardOfDirectors"),
        aiQuestionTypes=("지배구조",),
    ),
    DataEntry(
        name="affiliate",
        label="관계기업투자",
        category="report",
        dataType="dataframe",
        description="관계기업/공동기업 투자 변동 시계열. 지분법손익, 기초/기말 장부가 포함.",
        modulePath="dartlab.providers.dart.docs.finance.affiliate",
        funcName="affiliate",
        extractor=lambda r: r.movementDf,
        requires="docs",
        analysisHints=(
            "관계기업 지분법손익이 연결 실적에 미치는 영향",
            "투자 포트폴리오 변동(취득/처분) 추적",
        ),
        relatedModules=("subsidiary", "investmentInOther", "affiliateGroup"),
        aiQuestionTypes=("투자", "관계사"),
        aiKeywords=("관계사",),
    ),
    DataEntry(
        name="investmentInOther",
        label="타법인출자",
        category="report",
        dataType="dataframe",
        description="타법인 출자 현황. 투자목적, 지분율, 장부가 등.",
        modulePath="dartlab.providers.dart.docs.finance.investmentInOther",
        funcName="investmentInOther",
        extractor=lambda r: r.investmentDf,
        requires="docs",
        analysisHints=("비핵심 투자 비중과 수익성",),
        relatedModules=("subsidiary", "affiliateGroup"),
        maxRows=20,
        aiQuestionTypes=("성장성", "투자", "관계사"),
        aiKeywords=("출자",),
    ),
    DataEntry(
        name="companyOverviewDetail",
        label="회사개요",
        category="report",
        dataType="dict",
        description="설립일, 상장일, 대표이사, 주소, 주요사업 등 기본 정보.",
        modulePath="dartlab.providers.dart.docs.finance.companyOverviewDetail",
        funcName="companyOverviewDetail",
        extractor=lambda r: {
            "foundedDate": r.foundedDate,
            "listedDate": r.listedDate,
            "address": r.address,
            "ceo": r.ceo,
            "mainBusiness": r.mainBusiness,
            "website": r.website,
        },
        requires="docs",
    ),
    DataEntry(
        name="holderOverview",
        label="주주현황",
        category="report",
        dataType="custom",
        description="5% 이상 주주, 소액주주 현황, 의결권 현황. majorHolder보다 상세한 주주 구성.",
        modulePath="dartlab.providers.dart.docs.finance.majorHolder",
        funcName="holderOverview",
        extractor=None,
        requires="docs",
        analysisHints=(
            "5% 이상 대량보유 주주 변동 추적",
            "소액주주 비율과 유통주식 비율",
        ),
        relatedModules=("majorHolder", "shareCapital"),
        aiQuestionTypes=("지배구조",),
        aiKeywords=("주주",),
    ),
    # ═══════════════════════════════════════════════════════
]
